/**
 * PostgreSQL implementation of `KnowledgeWriteStore`.
 *
 * Same capability as `sqlite-write-store.ts`, different engine — and deliberately not
 * the same code: what the two implementations share is the port (`write-store.ts`),
 * the section CONTENT (same reads, guards and writes in the same order) and the
 * domain errors. Everything dialect-shaped lives here: the PG schema, genuinely async
 * transactions, whole-section retry, row locks and conflict translation.
 *
 * HOW EACH REQUIREMENT OF THE PORT IS MET
 * ---------------------------------------
 * - PROMISE boundary: every method is honestly async against a networked driver. An
 *   `await` between BEGIN and COMMIT is safe here, which is exactly what the
 *   write-port base contrasts with the SQLite implementation's strictly synchronous
 *   section.
 * - ATOMICITY: each operation's whole section runs in one `db.transaction`. Any
 *   rejection rolls all of it back. Every section is a NAMED async function invoked
 *   through a non-async arrow (`db.transaction((tx) => section(tx, input))`) — the
 *   shape the transaction-atomicity gate requires, so no `async` callback literal
 *   ever reaches a `.transaction(` call site.
 * - RETRY: `withPgRetry` wraps the WHOLE section (BEGIN through COMMIT), never a
 *   single statement. Sections are idempotent under whole-section replay: every row
 *   id is pre-generated by the caller, so a replay after a commit whose
 *   acknowledgement was lost surfaces as a conflict (or a get-or-create hit) instead
 *   of duplicating anything.
 * - CONFLICTS AS VOCABULARY: SQLSTATE 23505 is translated to `WriteConflictError`
 *   (with the constraint name the server reported) before it can cross the port
 *   boundary. `withPgRetry` classifies that as a unique-violation and never retries
 *   it into a false success.
 *
 * SERIALIZATION POINTS (where SQLite's single writer was the lock)
 * ----------------------------------------------------------------
 * Under SQLite every section below serialized on the single-writer transaction.
 * PostgreSQL runs sections concurrently, so each guard takes the row lock that makes
 * its check-then-write atomic — the "row-lock form" of the claims
 * `revision-version.ts` freezes:
 *
 *   appendRevision / commitMergedRevision  lock the ENTRY row (`FOR UPDATE`) before
 *                                          reading MAX(version): two allocators can
 *                                          never observe the same maximum.
 *   getOrCreateActiveDraft                 locks the ENTRY row before the active-draft
 *                                          re-check (no unique index covers
 *                                          (entry, author, status), so the lock is
 *                                          what keeps two creators from both passing).
 *   createSubmissionGuarded / updateDraftContent / rebaseDraftContent /
 *   archivePersonalEntry                   lock the DRAFT row: a submit and an edit
 *                                          serialize, so "no open submission" and
 *                                          "supersede the open submission" can never
 *                                          interleave into two pending requests.
 *   markSubmissionConflict / commitMergedRevision / approveStandalonePublish /
 *   withdrawSubmissionGuarded / setSubmissionReviewVerdict
 *                                          lock the SUBMISSION row before the status
 *                                          re-check: two reviewers serialize, and the
 *                                          loser re-reads the winner's verdict.
 *
 * Lock order is always submission → entry and never the reverse, so concurrent
 * approve + direct-append cannot deadlock.
 */
import { WriteConflictError } from "@server/db/backend/write-port";
import { isPgUniqueViolation } from "@server/db/pg-errors";
import { withPgRetry } from "@server/db/pg-retry";
import {
	aclEvents,
	aclGrants,
	knowledgeCollections,
	knowledgeDrafts,
	knowledgeEntries,
	knowledgeEntryLinks,
	knowledgeInjectionEvents,
	knowledgeLevels,
	knowledgePackActivations,
	knowledgeRevisions,
	knowledgeSubmissions,
	knowledgeTags,
	knowledgeTagTypes,
	narratorWhitelistDirs,
	specFileRevisions,
	specNamespaceFiles,
	specNamespaces,
	specProtectedTasks,
} from "@server/db/postgres-schema";
import { ValidationError } from "@server/lib/errors";
import { generateId } from "@server/lib/id";
import { and, desc, eq, inArray, isNull, or } from "drizzle-orm";
import type { BunSQLDatabase } from "drizzle-orm/bun-sql";
import { KNOWLEDGE_REVISION_VERSION_BASE } from "./revision-version";
import type {
	AclAuditEventWrite,
	AclGrantRowWrite,
	AppendRevisionWrite,
	ApproveStandalonePublishWrite,
	CommitMergedRevisionWrite,
	CreateCollectionWrite,
	CreateEntryLinkWrite,
	CreateEntryWrite,
	CreateSubmissionWrite,
	EnsureSpecNamespaceWrite,
	ForkSpecNamespaceWrite,
	GetOrCreateActiveDraftWrite,
	InvalidatedSubmissionRef,
	KnowledgeCollectionRow,
	KnowledgeDraftRow,
	KnowledgeEntryLinkRow,
	KnowledgeLevelRowWrite,
	KnowledgeSubmissionRow,
	KnowledgeTagRowWrite,
	KnowledgeTagTypeRowWrite,
	KnowledgeWriteStore,
	MarkSubmissionConflictWrite,
	RebaseDraftContentWrite,
	RecordInjectionEventsWrite,
	RecordPackActivationWrite,
	RenameKnowledgeLevelWrite,
	SetSubmissionVerdictWrite,
	SpecFileWriteResult,
	SpecNamespaceRow,
	SpecProtectedLockRow,
	UpdateCollectionFieldsWrite,
	UpdateDraftContentWrite,
	UpdateEntryAclFieldsWrite,
	UpdateEntryMetaWrite,
	WriteSpecFileRevisionWrite,
} from "./write-store";
import {
	CLAIMABLE_SUBMISSION_STATUSES,
	CLOSED_ON_ENTRY_DELETE_STATUSES,
	OPEN_SUBMISSION_SCAN_LIMIT,
	SUPERSEDABLE_SUBMISSION_STATUSES,
	WITHDRAWABLE_SUBMISSION_STATUSES,
} from "./write-store";

/** Transaction handle as produced by `db.transaction(async (tx) => …)`. PG-side only. */
type PgTransaction = Parameters<Parameters<BunSQLDatabase["transaction"]>[0]>[0];

/** The whole grant-delete section, named so the transaction call site stays a
 *  non-async arrow (see the header). */
async function deleteAclGrantSection(
	tx: PgTransaction,
	input: {
		grantId: string;
		writeSibling: {
			scopeType: string;
			scopeId: string | null;
			principalType: string;
			principalId: string;
		} | null;
	},
): Promise<void> {
	await tx.delete(aclGrants).where(eq(aclGrants.id, input.grantId));
	const sibling = input.writeSibling;
	if (sibling) {
		// The credential row and its write-capability sibling represented ONE grant in
		// the knowledge vocabulary; leaving the sibling behind would keep the authority
		// the caller just revoked.
		await tx
			.delete(aclGrants)
			.where(
				and(
					eq(aclGrants.scopeType, sibling.scopeType),
					sibling.scopeId === null
						? isNull(aclGrants.scopeId)
						: eq(aclGrants.scopeId, sibling.scopeId),
					eq(aclGrants.principalType, sibling.principalType),
					eq(aclGrants.principalId, sibling.principalId),
					eq(aclGrants.capability, "write"),
					isNull(aclGrants.domainKind),
				),
			);
	}
}

/** How deep `cause` chains are followed when looking for the driver error's detail. */
const MAX_CAUSE_DEPTH = 8;

/**
 * The constraint name the server attached to a unique violation, when it reported one.
 * Bun SQL surfaces it as `PostgresError.constraint`; Drizzle may wrap the driver error
 * under `cause`, so the chain is walked with the same bound `pg-errors.ts` uses.
 */
function extractConstraintName(error: unknown): string | null {
	let current: unknown = error;
	for (let depth = 0; depth < MAX_CAUSE_DEPTH; depth++) {
		if (!current || typeof current !== "object") return null;
		const constraint = (current as Record<string, unknown>).constraint;
		if (typeof constraint === "string" && constraint.length > 0) return constraint;
		current = (current as Record<string, unknown>).cause;
	}
	return null;
}

/**
 * Translate a unique violation into port vocabulary; everything else passes through.
 * The original error rides as `cause`, which keeps the SQLSTATE reachable for
 * classification — `withPgRetry` sees a unique-violation, not a retryable failure.
 */
function rethrowAsPortError(error: unknown): never {
	if (isPgUniqueViolation(error)) {
		throw new WriteConflictError("write conflicts with an existing row", {
			constraint: extractConstraintName(error),
			cause: error,
		});
	}
	throw error;
}

/** Translate conflicts for every write, including UPDATE races, after the whole
 * retry unit has rolled back. Never retry one statement inside a failed transaction. */
async function retryKnowledgeWrite<T>(
	run: () => Promise<T>,
	options: Parameters<typeof withPgRetry>[1],
): Promise<T> {
	try {
		return await withPgRetry(run, options);
	} catch (error) {
		if (error instanceof WriteConflictError) throw error;
		rethrowAsPortError(error);
	}
}

// ─────────────────────────────────────────────────────────────────────────────
// Row locks and shared section helpers
// ─────────────────────────────────────────────────────────────────────────────

/** Take the entry row lock (`FOR UPDATE`): the serialization point for version
 *  allocation and get-or-create-draft. No row means the entry does not exist; the
 *  subsequent FK then fails loudly, exactly like the counter claim would. */
async function lockEntry(tx: PgTransaction, entryId: string): Promise<void> {
	await tx
		.select({ id: knowledgeEntries.id })
		.from(knowledgeEntries)
		.where(eq(knowledgeEntries.id, entryId))
		.for("update")
		.limit(1);
}

/** Take the draft row lock: the serialization point for submit-vs-edit races. */
async function lockDraft(tx: PgTransaction, draftId: string): Promise<void> {
	await tx
		.select({ id: knowledgeDrafts.id })
		.from(knowledgeDrafts)
		.where(eq(knowledgeDrafts.id, draftId))
		.for("update")
		.limit(1);
}

/** Take the submission row lock: the serialization point for concurrent reviewers. */
async function lockSubmission(tx: PgTransaction, submissionId: string): Promise<void> {
	await tx
		.select({ id: knowledgeSubmissions.id })
		.from(knowledgeSubmissions)
		.where(eq(knowledgeSubmissions.id, submissionId))
		.for("update")
		.limit(1);
}

/**
 * Claim the next revision version for `entryId`. MUST be called with the entry row
 * lock already held (see {@link lockEntry}): the lock is what makes the MAX read and
 * the following insert atomic against concurrent allocators. This is the row-lock
 * form of the claim `revision-version.ts` freezes for the counter-column design.
 */
async function claimNextRevisionVersion(tx: PgTransaction, entryId: string): Promise<number> {
	const rows = await tx
		.select({ v: knowledgeRevisions.version })
		.from(knowledgeRevisions)
		.where(eq(knowledgeRevisions.entryId, entryId))
		.orderBy(desc(knowledgeRevisions.version))
		.limit(1);
	return (rows[0]?.v ?? KNOWLEDGE_REVISION_VERSION_BASE - 1) + 1;
}

/** PG twin of the SQLite helper: close the draft's open PENDING submissions. */
async function supersedeOpenSubmissions(
	tx: PgTransaction,
	draftId: string,
	now: string,
): Promise<InvalidatedSubmissionRef[]> {
	const stale = await tx
		.select({
			id: knowledgeSubmissions.id,
			submitterUserId: knowledgeSubmissions.submitterUserId,
		})
		.from(knowledgeSubmissions)
		.where(
			and(
				eq(knowledgeSubmissions.draftId, draftId),
				inArray(knowledgeSubmissions.status, [...SUPERSEDABLE_SUBMISSION_STATUSES]),
			),
		)
		.limit(OPEN_SUBMISSION_SCAN_LIMIT);
	if (stale.length === 0) return stale;
	await tx
		.update(knowledgeSubmissions)
		.set({ status: "superseded", reviewedAt: now })
		.where(
			and(
				eq(knowledgeSubmissions.draftId, draftId),
				inArray(knowledgeSubmissions.status, [...SUPERSEDABLE_SUBMISSION_STATUSES]),
			),
		);
	return stale;
}

// ─────────────────────────────────────────────────────────────────────────────
// The atomic sections, each one named so the transaction call site stays a
// non-async arrow (see the header) and one reviewer-readable unit.
// ─────────────────────────────────────────────────────────────────────────────

async function createEntrySection(tx: PgTransaction, input: CreateEntryWrite): Promise<void> {
	try {
		// Entry first: revisions.entryId has the FK, entries.currentRevisionId
		// deliberately does not — same ordering as the SQLite section.
		await tx.insert(knowledgeEntries).values({
			id: input.entryId,
			collectionId: input.collectionId,
			title: input.title,
			slug: input.slug,
			currentRevisionId: input.revisionId,
			currentContent: input.content,
			currentKeywords: input.currentKeywords,
			tagsJson: input.tagsJson,
			keywordsJson: input.keywordsJson,
			metadataJson: input.metadataJson,
			ownerUserId: input.ownerUserId,
			status: "active",
			createdAt: input.now,
			updatedAt: input.now,
		});
		await tx.insert(knowledgeRevisions).values({
			id: input.revisionId,
			entryId: input.entryId,
			version: 1,
			format: input.format,
			content: input.content,
			contentHash: input.contentHash,
			changeNote: input.changeNote,
			authorUserId: input.authorUserId,
			createdAt: input.now,
		});
	} catch (error) {
		rethrowAsPortError(error);
	}
}

async function appendRevisionSection(
	tx: PgTransaction,
	input: AppendRevisionWrite,
): Promise<{ version: number }> {
	// The entry row lock is the allocation authority: two concurrent appenders
	// serialize here instead of racing MAX(version)+1.
	await lockEntry(tx, input.entryId);
	const version = await claimNextRevisionVersion(tx, input.entryId);
	await tx.insert(knowledgeRevisions).values({
		id: input.revisionId,
		entryId: input.entryId,
		version,
		format: input.format,
		content: input.content,
		contentHash: input.contentHash,
		changeNote: input.changeNote,
		authorUserId: input.authorUserId,
		baseRevisionId: null,
		createdAt: input.now,
	});
	await tx
		.update(knowledgeEntries)
		.set({
			currentRevisionId: input.revisionId,
			currentContent: input.content,
			updatedAt: input.now,
		})
		.where(eq(knowledgeEntries.id, input.entryId));
	return { version };
}

async function recordInjectionEventsSection(
	tx: PgTransaction,
	input: RecordInjectionEventsWrite,
): Promise<void> {
	for (const hit of input.hits) {
		// ON CONFLICT DO NOTHING: the portable spelling of the
		// (narrator, compact_seq, entry) dedupe, shared with SQLite.
		await tx
			.insert(knowledgeInjectionEvents)
			.values({
				id: hit.id,
				narratorId: input.narratorId,
				compactSeq: input.compactSeq,
				entryId: hit.entryId,
				entryRevisionId: hit.entryRevisionId,
				source: input.source,
				triggerMessageId: input.triggerMessageId,
				triggerToolCallId: input.triggerToolCallId,
				summary: hit.summary,
				createdAt: input.now,
			})
			.onConflictDoNothing();
	}
}

async function getOrCreateActiveDraftSection(
	tx: PgTransaction,
	input: GetOrCreateActiveDraftWrite,
): Promise<KnowledgeDraftRow> {
	// No unique index covers (entry, author, status), so the ENTRY row lock is what
	// keeps two concurrent creators from both passing the re-check.
	await lockEntry(tx, input.entryId);
	const existing = await tx
		.select()
		.from(knowledgeDrafts)
		.where(
			and(
				eq(knowledgeDrafts.entryId, input.entryId),
				eq(knowledgeDrafts.authorUserId, input.authorUserId),
				inArray(knowledgeDrafts.status, ["active"]),
			),
		)
		.limit(1);
	if (existing[0]) return existing[0];
	const [draft] = await tx
		.insert(knowledgeDrafts)
		.values({
			id: input.draftId,
			entryId: input.entryId,
			authorUserId: input.authorUserId,
			name: input.name,
			baseRevisionId: input.baseRevisionId,
			content: input.content,
			contentHash: input.contentHash,
			format: "markdown",
			status: "active",
			createdAt: input.now,
			updatedAt: input.now,
		})
		.returning();
	if (!draft) throw new Error("draft insert returned no row");
	return draft;
}

async function archivePersonalEntrySection(
	tx: PgTransaction,
	input: { draftId: string; now: string },
): Promise<InvalidatedSubmissionRef[]> {
	await lockDraft(tx, input.draftId);
	const stale = await tx
		.select({
			id: knowledgeSubmissions.id,
			submitterUserId: knowledgeSubmissions.submitterUserId,
		})
		.from(knowledgeSubmissions)
		.where(
			and(
				eq(knowledgeSubmissions.draftId, input.draftId),
				inArray(knowledgeSubmissions.status, [...CLOSED_ON_ENTRY_DELETE_STATUSES]),
			),
		)
		.limit(OPEN_SUBMISSION_SCAN_LIMIT);
	await tx
		.update(knowledgeDrafts)
		.set({ status: "archived", updatedAt: input.now })
		.where(eq(knowledgeDrafts.id, input.draftId));
	await tx
		.update(knowledgeSubmissions)
		.set({ status: "withdrawn", reviewedAt: input.now })
		.where(
			and(
				eq(knowledgeSubmissions.draftId, input.draftId),
				inArray(knowledgeSubmissions.status, [...CLOSED_ON_ENTRY_DELETE_STATUSES]),
			),
		);
	return stale;
}

async function updateDraftContentSection(
	tx: PgTransaction,
	input: UpdateDraftContentWrite,
): Promise<InvalidatedSubmissionRef[]> {
	await lockDraft(tx, input.draftId);
	await tx
		.update(knowledgeDrafts)
		.set({
			content: input.content,
			contentHash: input.contentHash,
			...(input.name !== undefined ? { name: input.name } : {}),
			updatedAt: input.now,
		})
		.where(eq(knowledgeDrafts.id, input.draftId));
	return supersedeOpenSubmissions(tx, input.draftId, input.now);
}

async function rebaseDraftContentSection(
	tx: PgTransaction,
	input: RebaseDraftContentWrite,
): Promise<InvalidatedSubmissionRef[]> {
	await lockDraft(tx, input.draftId);
	await tx
		.update(knowledgeDrafts)
		.set({
			content: input.content,
			contentHash: input.contentHash,
			baseRevisionId: input.baseRevisionId,
			updatedAt: input.now,
		})
		.where(eq(knowledgeDrafts.id, input.draftId));
	return supersedeOpenSubmissions(tx, input.draftId, input.now);
}

async function createSubmissionSection(
	tx: PgTransaction,
	input: CreateSubmissionWrite,
): Promise<KnowledgeSubmissionRow> {
	// The draft row lock serializes submit-vs-edit: an updateDraftContent that
	// supersedes the open request can never interleave with this guard's
	// "no open request" read.
	await lockDraft(tx, input.draftId);
	const open = await tx
		.select({ id: knowledgeSubmissions.id, status: knowledgeSubmissions.status })
		.from(knowledgeSubmissions)
		.where(
			and(
				eq(knowledgeSubmissions.draftId, input.draftId),
				inArray(knowledgeSubmissions.status, [...CLAIMABLE_SUBMISSION_STATUSES]),
			),
		)
		.limit(1);
	if (open[0]) {
		throw new ValidationError(
			open[0].status === "conflict"
				? `This personal entry has a publish request in conflict (${open[0].id}). ` +
						"Withdraw it and publish again, or ask a reviewer to resolve the conflict."
				: `This personal entry already has a publish request awaiting review (${open[0].id}). ` +
						"Withdraw it first if you want to replace it.",
		);
	}
	const [submission] = await tx
		.insert(knowledgeSubmissions)
		.values({
			id: input.submissionId,
			draftId: input.draftId,
			entryId: input.entryId,
			collectionId: input.collectionId,
			title: input.title,
			submitterUserId: input.submitterUserId,
			baseRevisionId: input.baseRevisionId,
			proposedContent: input.proposedContent,
			keywordsJson: input.keywordsJson,
			changeNote: input.changeNote,
			previousSubmissionId: input.previousSubmissionId,
			round: input.round > 0 ? input.round : 1,
			status: "pending",
			createdAt: input.now,
		})
		.returning();
	if (!submission) throw new Error("submission insert returned no row");
	return submission;
}

async function setSubmissionVerdictSection(
	tx: PgTransaction,
	input: SetSubmissionVerdictWrite,
): Promise<void> {
	await lockSubmission(tx, input.submissionId);
	await tx
		.update(knowledgeSubmissions)
		.set({
			status: input.status,
			verdict: input.verdict,
			findingsJson: input.findingsJson,
			reviewerUserId: input.reviewerUserId,
			reviewedAt: input.now,
		})
		.where(eq(knowledgeSubmissions.id, input.submissionId));
}

async function markSubmissionConflictSection(
	tx: PgTransaction,
	input: MarkSubmissionConflictWrite,
): Promise<void> {
	await lockSubmission(tx, input.submissionId);
	const fresh = await tx
		.select({ status: knowledgeSubmissions.status })
		.from(knowledgeSubmissions)
		.where(eq(knowledgeSubmissions.id, input.submissionId))
		.limit(1);
	if (
		!fresh[0] ||
		!(CLAIMABLE_SUBMISSION_STATUSES as readonly string[]).includes(fresh[0].status)
	) {
		throw new ValidationError("Submission was already reviewed by someone else");
	}
	await tx
		.update(knowledgeSubmissions)
		.set({
			status: "conflict",
			verdict: "approve",
			findingsJson: input.findingsJson,
			reviewerUserId: input.reviewerUserId,
			reviewedAt: input.now,
		})
		.where(eq(knowledgeSubmissions.id, input.submissionId));
}

async function approveStandaloneSection(
	tx: PgTransaction,
	input: ApproveStandalonePublishWrite,
): Promise<void> {
	await lockSubmission(tx, input.submissionId);
	const fresh = await tx
		.select({ status: knowledgeSubmissions.status })
		.from(knowledgeSubmissions)
		.where(eq(knowledgeSubmissions.id, input.submissionId))
		.limit(1);
	if (
		!fresh[0] ||
		!(CLAIMABLE_SUBMISSION_STATUSES as readonly string[]).includes(fresh[0].status)
	) {
		throw new ValidationError("Submission was already reviewed by someone else");
	}

	// Resolve a unique slug within the collection (append -2, -3, …).
	let slug = input.baseSlug;
	let n = 1;
	for (;;) {
		const clash = await tx
			.select({ id: knowledgeEntries.id })
			.from(knowledgeEntries)
			.where(
				and(eq(knowledgeEntries.collectionId, input.collectionId), eq(knowledgeEntries.slug, slug)),
			)
			.limit(1);
		if (!clash[0]) break;
		n += 1;
		slug = `${input.baseSlug}-${n}`;
	}

	try {
		await tx.insert(knowledgeEntries).values({
			id: input.entryId,
			collectionId: input.collectionId,
			title: input.title,
			slug,
			currentRevisionId: input.revisionId,
			currentContent: input.proposedContent,
			tagsJson: [],
			keywordsJson: input.keywords,
			currentKeywords: input.keywords.length > 0 ? input.keywords.join(" ") : null,
			ownerUserId: input.submitterUserId,
			status: "active",
			createdAt: input.now,
			updatedAt: input.now,
		});
		await tx.insert(knowledgeRevisions).values({
			id: input.revisionId,
			entryId: input.entryId,
			version: 1,
			format: "markdown",
			content: input.proposedContent,
			contentHash: input.contentHash,
			changeNote: input.changeNote,
			authorUserId: input.submitterUserId,
			createdAt: input.now,
		});
	} catch (error) {
		rethrowAsPortError(error);
	}
	await tx
		.update(knowledgeSubmissions)
		.set({
			status: "approved",
			entryId: input.entryId,
			reviewerUserId: input.reviewerUserId,
			reviewedAt: input.now,
			findingsJson: input.findingsJson,
			mergedRevisionId: input.revisionId,
		})
		.where(eq(knowledgeSubmissions.id, input.submissionId));
	await tx
		.update(knowledgeDrafts)
		.set({ entryId: input.entryId, status: "archived", updatedAt: input.now })
		.where(eq(knowledgeDrafts.id, input.draftId));
}

async function commitMergedRevisionSection(
	tx: PgTransaction,
	input: CommitMergedRevisionWrite,
): Promise<{ version: number }> {
	// Lock order is submission → entry, everywhere: a concurrent appendRevision takes
	// only the entry lock, so the two can never deadlock, and two reviewers serialize
	// on the submission row.
	await lockSubmission(tx, input.submissionId);
	const fresh = await tx
		.select({ status: knowledgeSubmissions.status })
		.from(knowledgeSubmissions)
		.where(eq(knowledgeSubmissions.id, input.submissionId))
		.limit(1);
	if (
		!fresh[0] ||
		!(CLAIMABLE_SUBMISSION_STATUSES as readonly string[]).includes(fresh[0].status)
	) {
		throw new ValidationError("Submission was already reviewed by someone else");
	}

	await lockEntry(tx, input.entryId);
	const version = await claimNextRevisionVersion(tx, input.entryId);
	await tx.insert(knowledgeRevisions).values({
		id: input.revisionId,
		entryId: input.entryId,
		version,
		format: "markdown",
		content: input.content,
		contentHash: input.contentHash,
		changeNote: input.changeNote,
		authorUserId: input.submitterUserId,
		baseRevisionId: input.baseRevisionId,
		createdAt: input.now,
	});
	await tx
		.update(knowledgeEntries)
		.set({
			currentRevisionId: input.revisionId,
			currentContent: input.content,
			updatedAt: input.now,
		})
		.where(eq(knowledgeEntries.id, input.entryId));
	await tx
		.update(knowledgeSubmissions)
		.set({
			status: "approved",
			reviewerUserId: input.reviewerUserId,
			reviewedAt: input.now,
			mergedRevisionId: input.revisionId,
		})
		.where(eq(knowledgeSubmissions.id, input.submissionId));
	await tx
		.update(knowledgeDrafts)
		.set({ status: "archived", updatedAt: input.now })
		.where(eq(knowledgeDrafts.id, input.draftId));
	return { version };
}

async function withdrawSubmissionSection(
	tx: PgTransaction,
	input: { submissionId: string; changeNote?: string; now: string },
): Promise<boolean> {
	await lockSubmission(tx, input.submissionId);
	const fresh = await tx
		.select({ status: knowledgeSubmissions.status })
		.from(knowledgeSubmissions)
		.where(eq(knowledgeSubmissions.id, input.submissionId))
		.limit(1);
	if (
		!fresh[0] ||
		!(WITHDRAWABLE_SUBMISSION_STATUSES as readonly string[]).includes(fresh[0].status)
	) {
		return false;
	}
	await tx
		.update(knowledgeSubmissions)
		.set({
			status: "withdrawn",
			reviewedAt: input.now,
			...(input.changeNote !== undefined ? { changeNote: input.changeNote } : {}),
		})
		.where(eq(knowledgeSubmissions.id, input.submissionId));
	return true;
}

async function renameKnowledgeLevelSection(
	tx: PgTransaction,
	input: RenameKnowledgeLevelWrite,
): Promise<void> {
	if (input.rename) {
		const { from, to } = input.rename;
		await tx
			.update(knowledgeEntries)
			.set({ classificationLevel: to })
			.where(eq(knowledgeEntries.classificationLevel, from));
		await tx
			.update(knowledgeCollections)
			.set({ defaultLevel: to })
			.where(eq(knowledgeCollections.defaultLevel, from));
		await tx
			.update(knowledgeCollections)
			.set({ classificationLevel: to })
			.where(eq(knowledgeCollections.classificationLevel, from));
		// Clearance credentials reference the level BY NAME; the rename rewrites them
		// in the same section or `rankOf` fails closed.
		await tx
			.update(aclGrants)
			.set({ domainValue: to })
			.where(and(eq(aclGrants.domainKind, "clearance"), eq(aclGrants.domainValue, from)));
	}
	await tx.update(knowledgeLevels).set(input.updates).where(eq(knowledgeLevels.id, input.levelId));
}

async function insertAclGrantRowsSection(
	tx: PgTransaction,
	rows: AclGrantRowWrite[],
): Promise<void> {
	try {
		for (const row of rows) {
			await tx.insert(aclGrants).values({
				id: row.id,
				scopeType: row.scopeType,
				scopeId: row.scopeId,
				principalType: row.principalType,
				principalId: row.principalId,
				capability: row.capability,
				domainKind: row.domainKind,
				domainValue: row.domainValue,
				grantedBy: row.grantedBy,
				createdAt: row.createdAt,
			});
		}
	} catch (error) {
		rethrowAsPortError(error);
	}
}

async function replaceUserKnowledgeGrantsSection(
	tx: PgTransaction,
	input: { principalType: string; principalId: string; rows: AclGrantRowWrite[] },
): Promise<void> {
	// Knowledge scope only — project/narrator memberships of the same principal are
	// other scopes and must survive the replacement.
	await tx
		.delete(aclGrants)
		.where(
			and(
				or(eq(aclGrants.scopeType, "global"), eq(aclGrants.scopeType, "knowledge_collection")),
				eq(aclGrants.principalType, input.principalType),
				eq(aclGrants.principalId, input.principalId),
			),
		);
	for (const row of input.rows) {
		await tx.insert(aclGrants).values({
			id: row.id,
			scopeType: row.scopeType,
			scopeId: row.scopeId,
			principalType: row.principalType,
			principalId: row.principalId,
			capability: row.capability,
			domainKind: row.domainKind,
			domainValue: row.domainValue,
			grantedBy: row.grantedBy,
			createdAt: row.createdAt,
		});
	}
}

async function recordPackActivationSection(
	tx: PgTransaction,
	input: RecordPackActivationWrite,
): Promise<void> {
	await tx
		.delete(narratorWhitelistDirs)
		.where(
			and(
				eq(narratorWhitelistDirs.narratorId, input.narratorId),
				eq(narratorWhitelistDirs.path, input.extractDir),
			),
		);
	await tx.insert(narratorWhitelistDirs).values({
		id: input.whitelistDirId,
		narratorId: input.narratorId,
		path: input.extractDir,
		accessLevel: "readWrite",
		enabled: true,
		createdAt: input.now,
	});
	await tx.insert(knowledgePackActivations).values({
		id: input.activationId,
		packId: input.packId,
		narratorId: input.narratorId,
		extractDir: input.extractDir,
		whitelistDirId: input.whitelistDirId,
		archiveHash: input.archiveHash,
		status: "active",
		createdAt: input.now,
	});
}

async function releasePackActivationSection(
	tx: PgTransaction,
	input: { activationId: string; whitelistDirId: string | null; now: string },
): Promise<void> {
	if (input.whitelistDirId) {
		await tx
			.delete(narratorWhitelistDirs)
			.where(eq(narratorWhitelistDirs.id, input.whitelistDirId));
	}
	await tx
		.update(knowledgePackActivations)
		.set({ status: "released", releasedAt: input.now })
		.where(eq(knowledgePackActivations.id, input.activationId));
}

async function writeSpecFileRevisionSection(
	tx: PgTransaction,
	input: WriteSpecFileRevisionWrite,
): Promise<SpecFileWriteResult> {
	const current = await tx
		.select()
		.from(specNamespaceFiles)
		.where(
			and(
				eq(specNamespaceFiles.namespaceId, input.namespaceId),
				eq(specNamespaceFiles.path, input.path),
			),
		)
		.limit(1);

	let locks: SpecProtectedLockRow[] = [];
	if (input.specTasks) {
		locks = await tx
			.select({
				id: specProtectedTasks.id,
				textHash: specProtectedTasks.textHash,
				text: specProtectedTasks.text,
				status: specProtectedTasks.status,
				completedAt: specProtectedTasks.completedAt,
			})
			.from(specProtectedTasks)
			.where(eq(specProtectedTasks.namespaceId, input.namespaceId));
		const protectedMutations = input.specTasks.detectProtectedMutations(locks);
		if (protectedMutations.length > 0 && !input.specTasks.allowProtectedTaskMutation) {
			// Nothing has been written yet; returning the verdict is a clean no-op, and
			// withPgRetry does not replay a non-error result.
			return { ok: false as const, protectedMutations };
		}
	}

	await tx.insert(specFileRevisions).values({
		id: input.revisionId,
		namespaceId: input.namespaceId,
		path: input.path,
		content: input.content,
		contentHash: input.contentHash,
		parentRevisionId: current[0]?.revisionId ?? null,
		sourceToolUseId: input.sourceToolUseId,
		sourceMessageId: input.sourceMessageId,
		createdBy: input.createdBy,
		createdAt: input.now,
	});

	if (current[0]) {
		await tx
			.update(specNamespaceFiles)
			.set({ revisionId: input.revisionId, deleted: false, updatedAt: input.now })
			.where(eq(specNamespaceFiles.id, current[0].id));
	} else {
		await tx.insert(specNamespaceFiles).values({
			id: input.fileIdForCreate,
			namespaceId: input.namespaceId,
			path: input.path,
			revisionId: input.revisionId,
			deleted: false,
			updatedAt: input.now,
		});
	}

	await tx
		.update(specNamespaces)
		.set({ updatedAt: input.now })
		.where(eq(specNamespaces.id, input.namespaceId));

	if (input.specTasks) {
		const existingByHash = new Map(locks.map((lock) => [lock.textHash, lock]));
		const protectedTasksInDoc = input.specTasks.tasks.filter((task) => task.protected);
		for (const task of protectedTasksInDoc) {
			const existing = existingByHash.get(task.textHash);
			if (!existing) {
				await tx.insert(specProtectedTasks).values({
					id: generateId(),
					namespaceId: input.namespaceId,
					textHash: task.textHash,
					text: task.text,
					status: task.status,
					firstRevisionId: input.revisionId,
					lastRevisionId: input.revisionId,
					createdAt: input.now,
					updatedAt: input.now,
					completedAt: task.status === "done" ? input.now : null,
				});
				continue;
			}
			await tx
				.update(specProtectedTasks)
				.set({
					status: task.status,
					lastRevisionId: input.revisionId,
					updatedAt: input.now,
					...(task.status === "done" && !existing.completedAt ? { completedAt: input.now } : {}),
				})
				.where(eq(specProtectedTasks.id, existing.id));
		}
		const hashesInDoc = protectedTasksInDoc.map((task) => task.textHash);
		for (const lock of locks) {
			if (lock.status !== "todo" && lock.status !== "doing" && lock.status !== "blocked") {
				continue;
			}
			if (hashesInDoc.includes(lock.textHash)) continue;
			await tx
				.update(specProtectedTasks)
				.set({
					status: "deleted",
					deletedAt: input.now,
					updatedAt: input.now,
					lastRevisionId: input.revisionId,
				})
				.where(eq(specProtectedTasks.id, lock.id));
		}
	}
	return { ok: true as const };
}

async function forkSpecNamespaceSection(
	tx: PgTransaction,
	input: ForkSpecNamespaceWrite,
): Promise<{ created: boolean }> {
	const existingChild = await tx
		.select({ id: specNamespaces.id })
		.from(specNamespaces)
		.where(eq(specNamespaces.narratorId, input.childNarratorId))
		.limit(1);
	if (existingChild[0]) return { created: false as const };
	await tx.insert(specNamespaces).values({
		id: input.childNamespaceId,
		narratorId: input.childNarratorId,
		forkedFromNamespaceId: input.parentNamespaceId,
		createdAt: input.now,
		updatedAt: input.now,
	});
	const parentFiles = await tx
		.select()
		.from(specNamespaceFiles)
		.where(
			and(
				eq(specNamespaceFiles.namespaceId, input.parentNamespaceId),
				eq(specNamespaceFiles.deleted, false),
			),
		);
	for (const file of parentFiles) {
		await tx.insert(specNamespaceFiles).values({
			id: generateId(),
			namespaceId: input.childNamespaceId,
			path: file.path,
			revisionId: file.revisionId,
			deleted: false,
			updatedAt: input.now,
		});
	}
	const parentProtectedTasks = await tx
		.select()
		.from(specProtectedTasks)
		.where(eq(specProtectedTasks.namespaceId, input.parentNamespaceId));
	for (const task of parentProtectedTasks) {
		await tx.insert(specProtectedTasks).values({
			id: generateId(),
			namespaceId: input.childNamespaceId,
			textHash: task.textHash,
			text: task.text,
			status: task.status,
			firstRevisionId: task.firstRevisionId,
			lastRevisionId: task.lastRevisionId,
			createdAt: input.now,
			updatedAt: input.now,
			completedAt: task.completedAt,
			deletedAt: task.deletedAt,
		});
	}
	return { created: true as const };
}

async function resetSpecNamespaceSection(
	tx: PgTransaction,
	input: { namespaceId: string; now: string },
): Promise<void> {
	await tx.delete(specNamespaceFiles).where(eq(specNamespaceFiles.namespaceId, input.namespaceId));
	await tx
		.update(specProtectedTasks)
		.set({ status: "deleted", deletedAt: input.now, updatedAt: input.now })
		.where(
			and(
				eq(specProtectedTasks.namespaceId, input.namespaceId),
				inArray(specProtectedTasks.status, ["todo", "doing", "blocked"]),
			),
		);
	await tx
		.update(specNamespaces)
		.set({ updatedAt: input.now })
		.where(eq(specNamespaces.id, input.namespaceId));
}

// ─────────────────────────────────────────────────────────────────────────────
// The store
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Build the store over a caller-supplied handle. The factory takes the database rather
 * than opening one: who owns the connection (and its lifecycle) is a composition-root
 * decision, and tests supply a handle pointed at a throwaway container.
 */
export function createPostgresKnowledgeWriteStore(db: BunSQLDatabase): KnowledgeWriteStore {
	return {
		async createCollection(input: CreateCollectionWrite): Promise<KnowledgeCollectionRow> {
			return retryKnowledgeWrite(
				async () => {
					try {
						const [created] = await db
							.insert(knowledgeCollections)
							.values({
								id: input.id,
								name: input.name,
								slug: input.slug,
								description: input.description,
								projectId: input.projectId,
								ownerUserId: input.ownerUserId,
								createdAt: input.now,
								updatedAt: input.now,
							})
							.returning();
						if (!created) throw new Error("collection insert returned no row");
						return created;
					} catch (error) {
						rethrowAsPortError(error);
					}
				},
				{ label: "knowledge.createCollection" },
			);
		},

		async createEntryWithFirstRevision(input: CreateEntryWrite): Promise<void> {
			await retryKnowledgeWrite(() => db.transaction((tx) => createEntrySection(tx, input)), {
				label: "knowledge.createEntry",
			});
		},

		async updateEntryMeta(input: UpdateEntryMetaWrite): Promise<void> {
			await retryKnowledgeWrite(
				async () => {
					await db
						.update(knowledgeEntries)
						.set({
							...(input.title !== undefined ? { title: input.title } : {}),
							...(input.tagsJson !== undefined ? { tagsJson: input.tagsJson } : {}),
							...(input.keywordsJson !== undefined ? { keywordsJson: input.keywordsJson } : {}),
							...(input.currentKeywords !== undefined
								? { currentKeywords: input.currentKeywords }
								: {}),
							...(input.metadataJson !== undefined ? { metadataJson: input.metadataJson } : {}),
							...(input.status !== undefined ? { status: input.status } : {}),
							updatedAt: input.now,
						})
						.where(eq(knowledgeEntries.id, input.entryId));
				},
				{ label: "knowledge.updateEntryMeta" },
			);
		},

		async appendRevision(input: AppendRevisionWrite): Promise<{ version: number }> {
			return retryKnowledgeWrite(() => db.transaction((tx) => appendRevisionSection(tx, input)), {
				label: "knowledge.addRevision",
			});
		},

		async recordInjectionEvents(input: RecordInjectionEventsWrite): Promise<void> {
			if (input.hits.length === 0) return;
			await retryKnowledgeWrite(
				() => db.transaction((tx) => recordInjectionEventsSection(tx, input)),
				{
					label: "knowledge.recordInjectionEvents",
				},
			);
		},

		async getOrCreateActiveDraft(input: GetOrCreateActiveDraftWrite): Promise<KnowledgeDraftRow> {
			return retryKnowledgeWrite(
				() => db.transaction((tx) => getOrCreateActiveDraftSection(tx, input)),
				{
					label: "knowledge.getOrCreateActiveDraft",
				},
			);
		},

		async archivePersonalEntry(input: {
			draftId: string;
			now: string;
		}): Promise<InvalidatedSubmissionRef[]> {
			return retryKnowledgeWrite(
				() => db.transaction((tx) => archivePersonalEntrySection(tx, input)),
				{
					label: "knowledge.archivePersonalEntry",
				},
			);
		},

		async updateDraftContent(input: UpdateDraftContentWrite): Promise<InvalidatedSubmissionRef[]> {
			return retryKnowledgeWrite(
				() => db.transaction((tx) => updateDraftContentSection(tx, input)),
				{
					label: "knowledge.updateDraftContent",
				},
			);
		},

		async rebaseDraftContent(input: RebaseDraftContentWrite): Promise<InvalidatedSubmissionRef[]> {
			return retryKnowledgeWrite(
				() => db.transaction((tx) => rebaseDraftContentSection(tx, input)),
				{
					label: "knowledge.rebaseDraftContent",
				},
			);
		},

		async createSubmissionGuarded(input: CreateSubmissionWrite): Promise<KnowledgeSubmissionRow> {
			return retryKnowledgeWrite(() => db.transaction((tx) => createSubmissionSection(tx, input)), {
				label: "knowledge.createSubmission",
			});
		},

		async setSubmissionReviewVerdict(input: SetSubmissionVerdictWrite): Promise<void> {
			await retryKnowledgeWrite(
				() => db.transaction((tx) => setSubmissionVerdictSection(tx, input)),
				{
					label: "knowledge.setSubmissionVerdict",
				},
			);
		},

		async markSubmissionConflict(input: MarkSubmissionConflictWrite): Promise<void> {
			await retryKnowledgeWrite(
				() => db.transaction((tx) => markSubmissionConflictSection(tx, input)),
				{
					label: "knowledge.markSubmissionConflict",
				},
			);
		},

		async approveStandalonePublish(input: ApproveStandalonePublishWrite): Promise<void> {
			await retryKnowledgeWrite(() => db.transaction((tx) => approveStandaloneSection(tx, input)), {
				label: "knowledge.approveStandalone",
			});
		},

		async commitMergedRevision(input: CommitMergedRevisionWrite): Promise<{ version: number }> {
			return retryKnowledgeWrite(
				() => db.transaction((tx) => commitMergedRevisionSection(tx, input)),
				{
					label: "knowledge.commitMergedRevision",
				},
			);
		},

		async withdrawSubmissionGuarded(input: {
			submissionId: string;
			changeNote?: string;
			now: string;
		}): Promise<boolean> {
			return retryKnowledgeWrite(
				() => db.transaction((tx) => withdrawSubmissionSection(tx, input)),
				{
					label: "knowledge.withdrawSubmission",
				},
			);
		},

		async renameKnowledgeLevel(input: RenameKnowledgeLevelWrite): Promise<void> {
			await retryKnowledgeWrite(
				() => db.transaction((tx) => renameKnowledgeLevelSection(tx, input)),
				{
					label: "knowledge.renameKnowledgeLevel",
				},
			);
		},

		async insertAclGrantRows(rows: AclGrantRowWrite[]): Promise<void> {
			if (rows.length === 0) return;
			await retryKnowledgeWrite(() => db.transaction((tx) => insertAclGrantRowsSection(tx, rows)), {
				label: "knowledge.insertAclGrantRows",
			});
		},

		async replaceUserKnowledgeGrants(input: {
			principalType: string;
			principalId: string;
			rows: AclGrantRowWrite[];
		}): Promise<void> {
			await retryKnowledgeWrite(
				() => db.transaction((tx) => replaceUserKnowledgeGrantsSection(tx, input)),
				{ label: "knowledge.replaceUserKnowledgeGrants" },
			);
		},

		async recordPackActivation(input: RecordPackActivationWrite): Promise<void> {
			await retryKnowledgeWrite(
				() => db.transaction((tx) => recordPackActivationSection(tx, input)),
				{
					label: "knowledge.recordPackActivation",
				},
			);
		},

		async releasePackActivation(input: {
			activationId: string;
			whitelistDirId: string | null;
			now: string;
		}): Promise<void> {
			await retryKnowledgeWrite(
				() => db.transaction((tx) => releasePackActivationSection(tx, input)),
				{
					label: "knowledge.releasePackActivation",
				},
			);
		},

		async ensureSpecNamespace(input: EnsureSpecNamespaceWrite): Promise<SpecNamespaceRow> {
			return retryKnowledgeWrite(
				async () => {
					const existing = await db
						.select()
						.from(specNamespaces)
						.where(eq(specNamespaces.narratorId, input.narratorId))
						.limit(1);
					if (existing[0]) return existing[0];
					try {
						const [created] = await db
							.insert(specNamespaces)
							.values({
								id: input.namespaceId,
								narratorId: input.narratorId,
								createdAt: input.now,
								updatedAt: input.now,
							})
							.returning();
						if (!created) throw new Error("namespace insert returned no row");
						return created;
					} catch (error) {
						// Lost the create race: the winner's row is the answer. Only a
						// still-missing row means the failure was something else.
						const raced = await db
							.select()
							.from(specNamespaces)
							.where(eq(specNamespaces.narratorId, input.narratorId))
							.limit(1);
						if (raced[0]) return raced[0];
						throw error;
					}
				},
				{ label: "knowledge.ensureSpecNamespace" },
			);
		},

		async writeSpecFileRevision(input: WriteSpecFileRevisionWrite): Promise<SpecFileWriteResult> {
			return retryKnowledgeWrite(
				() => db.transaction((tx) => writeSpecFileRevisionSection(tx, input)),
				{
					label: "knowledge.writeSpecFileRevision",
				},
			);
		},

		async markSpecFileDeleted(input: { fileId: string; now: string }): Promise<void> {
			await retryKnowledgeWrite(
				async () => {
					await db
						.update(specNamespaceFiles)
						.set({ deleted: true, updatedAt: input.now })
						.where(eq(specNamespaceFiles.id, input.fileId));
				},
				{ label: "knowledge.markSpecFileDeleted" },
			);
		},

		async forkSpecNamespace(input: ForkSpecNamespaceWrite): Promise<{ created: boolean }> {
			return retryKnowledgeWrite(
				() => db.transaction((tx) => forkSpecNamespaceSection(tx, input)),
				{
					label: "knowledge.forkSpecNamespace",
				},
			);
		},

		async resetSpecNamespace(input: { namespaceId: string; now: string }): Promise<void> {
			await retryKnowledgeWrite(
				() => db.transaction((tx) => resetSpecNamespaceSection(tx, input)),
				{
					label: "knowledge.resetSpecNamespace",
				},
			);
		},

		// ── collections / entries: the remaining lifecycle writes ──

		async updateCollectionFields(input: UpdateCollectionFieldsWrite): Promise<void> {
			await retryKnowledgeWrite(
				async () => {
					await db
						.update(knowledgeCollections)
						.set({
							...(input.name !== undefined ? { name: input.name } : {}),
							...(input.description !== undefined ? { description: input.description } : {}),
							...(input.classificationLevel !== undefined
								? { classificationLevel: input.classificationLevel }
								: {}),
							...(input.controlledTagsJson !== undefined
								? { controlledTagsJson: input.controlledTagsJson }
								: {}),
							...(input.ownerUserId !== undefined ? { ownerUserId: input.ownerUserId } : {}),
							updatedAt: input.now,
						})
						.where(eq(knowledgeCollections.id, input.collectionId));
				},
				{ label: "knowledge.updateCollectionFields" },
			);
		},

		async deleteCollection(input: { collectionId: string }): Promise<void> {
			// Single statement: the entries/revisions/links inside go with the FK cascade,
			// and the FTS shadow rows with the delete trigger.
			await retryKnowledgeWrite(
				async () => {
					await db
						.delete(knowledgeCollections)
						.where(eq(knowledgeCollections.id, input.collectionId));
				},
				{ label: "knowledge.deleteCollection" },
			);
		},

		async updateEntryAclFields(input: UpdateEntryAclFieldsWrite): Promise<void> {
			await retryKnowledgeWrite(
				async () => {
					await db
						.update(knowledgeEntries)
						.set({
							...(input.classificationLevel !== undefined
								? { classificationLevel: input.classificationLevel }
								: {}),
							...(input.controlledTagsJson !== undefined
								? { controlledTagsJson: input.controlledTagsJson }
								: {}),
							...(input.reviewTagsJson !== undefined
								? { reviewTagsJson: input.reviewTagsJson }
								: {}),
							...(input.ownerUserId !== undefined ? { ownerUserId: input.ownerUserId } : {}),
							updatedAt: input.now,
						})
						.where(eq(knowledgeEntries.id, input.entryId));
				},
				{ label: "knowledge.updateEntryAclFields" },
			);
		},

		async deleteEntry(input: { entryId: string }): Promise<void> {
			await retryKnowledgeWrite(
				async () => {
					await db.delete(knowledgeEntries).where(eq(knowledgeEntries.id, input.entryId));
				},
				{ label: "knowledge.deleteEntry" },
			);
		},

		// ── entry links ──

		async createEntryLink(input: CreateEntryLinkWrite): Promise<KnowledgeEntryLinkRow> {
			return retryKnowledgeWrite(
				async () => {
					try {
						const [created] = await db
							.insert(knowledgeEntryLinks)
							.values({
								id: input.id,
								fromEntryId: input.fromEntryId,
								toEntryId: input.toEntryId,
								linkType: input.linkType,
								label: input.label,
								toRevisionId: input.toRevisionId,
								createdByUserId: input.createdByUserId,
								createdAt: input.now,
							})
							.returning();
						if (!created) throw new Error("entry link insert returned no row");
						return created;
					} catch (error) {
						rethrowAsPortError(error);
					}
				},
				{ label: "knowledge.createEntryLink" },
			);
		},

		async deleteEntryLink(input: { linkId: string }): Promise<void> {
			await retryKnowledgeWrite(
				async () => {
					await db.delete(knowledgeEntryLinks).where(eq(knowledgeEntryLinks.id, input.linkId));
				},
				{ label: "knowledge.deleteEntryLink" },
			);
		},

		// ── ACL admin CRUD ──

		async insertKnowledgeLevel(input: {
			id: string;
			name: string;
			rank: number;
			label: string | null;
			now: string;
		}): Promise<KnowledgeLevelRowWrite> {
			return retryKnowledgeWrite(
				async () => {
					try {
						const [row] = await db
							.insert(knowledgeLevels)
							.values({
								id: input.id,
								name: input.name,
								rank: input.rank,
								label: input.label,
								createdAt: input.now,
							})
							.returning();
						if (!row) throw new Error("level insert returned no row");
						return row;
					} catch (error) {
						rethrowAsPortError(error);
					}
				},
				{ label: "knowledge.insertKnowledgeLevel" },
			);
		},

		async deleteKnowledgeLevel(input: { levelId: string }): Promise<void> {
			await retryKnowledgeWrite(
				async () => {
					await db.delete(knowledgeLevels).where(eq(knowledgeLevels.id, input.levelId));
				},
				{ label: "knowledge.deleteKnowledgeLevel" },
			);
		},

		async insertKnowledgeTag(input: {
			id: string;
			name: string;
			collectionId: string | null;
			typeId: string | null;
			controlled: boolean;
			now: string;
		}): Promise<KnowledgeTagRowWrite> {
			return retryKnowledgeWrite(
				async () => {
					try {
						const [row] = await db
							.insert(knowledgeTags)
							.values({
								id: input.id,
								name: input.name,
								collectionId: input.collectionId,
								typeId: input.typeId,
								controlled: input.controlled,
								createdAt: input.now,
							})
							.returning();
						if (!row) throw new Error("tag insert returned no row");
						return row;
					} catch (error) {
						rethrowAsPortError(error);
					}
				},
				{ label: "knowledge.insertKnowledgeTag" },
			);
		},

		async updateKnowledgeTag(input: {
			tagId: string;
			name?: string;
			controlled?: boolean;
			typeId?: string | null;
		}): Promise<void> {
			await retryKnowledgeWrite(
				async () => {
					await db
						.update(knowledgeTags)
						.set({
							...(input.name !== undefined ? { name: input.name } : {}),
							...(input.controlled !== undefined ? { controlled: input.controlled } : {}),
							...(input.typeId !== undefined ? { typeId: input.typeId } : {}),
						})
						.where(eq(knowledgeTags.id, input.tagId));
				},
				{ label: "knowledge.updateKnowledgeTag" },
			);
		},

		async deleteKnowledgeTag(input: { tagId: string }): Promise<void> {
			await retryKnowledgeWrite(
				async () => {
					await db.delete(knowledgeTags).where(eq(knowledgeTags.id, input.tagId));
				},
				{ label: "knowledge.deleteKnowledgeTag" },
			);
		},

		async insertKnowledgeTagType(input: {
			id: string;
			name: string;
			sortOrder: number;
			now: string;
		}): Promise<KnowledgeTagTypeRowWrite> {
			return retryKnowledgeWrite(
				async () => {
					try {
						const [row] = await db
							.insert(knowledgeTagTypes)
							.values({
								id: input.id,
								name: input.name,
								builtin: false,
								sortOrder: input.sortOrder,
								createdAt: input.now,
							})
							.returning();
						if (!row) throw new Error("tag type insert returned no row");
						return row;
					} catch (error) {
						rethrowAsPortError(error);
					}
				},
				{ label: "knowledge.insertKnowledgeTagType" },
			);
		},

		async updateKnowledgeTagType(input: {
			tagTypeId: string;
			name?: string;
			sortOrder?: number;
		}): Promise<void> {
			await retryKnowledgeWrite(
				async () => {
					await db
						.update(knowledgeTagTypes)
						.set({
							...(input.name !== undefined ? { name: input.name } : {}),
							...(input.sortOrder !== undefined ? { sortOrder: input.sortOrder } : {}),
						})
						.where(eq(knowledgeTagTypes.id, input.tagTypeId));
				},
				{ label: "knowledge.updateKnowledgeTagType" },
			);
		},

		async deleteKnowledgeTagType(input: { tagTypeId: string }): Promise<void> {
			await retryKnowledgeWrite(
				async () => {
					// Tags referencing this type get type_id set to null via FK onDelete.
					await db.delete(knowledgeTagTypes).where(eq(knowledgeTagTypes.id, input.tagTypeId));
				},
				{ label: "knowledge.deleteKnowledgeTagType" },
			);
		},

		async deleteAclGrantWithWriteSibling(input: {
			grantId: string;
			writeSibling: {
				scopeType: string;
				scopeId: string | null;
				principalType: string;
				principalId: string;
			} | null;
		}): Promise<void> {
			await retryKnowledgeWrite(() => db.transaction((tx) => deleteAclGrantSection(tx, input)), {
				label: "knowledge.deleteAclGrantWithWriteSibling",
			});
		},

		async deleteUserKnowledgeGrants(input: {
			principalType: string;
			principalId: string;
		}): Promise<void> {
			await retryKnowledgeWrite(
				async () => {
					// Knowledge scope only: project/narrator memberships of the same principal
					// are other scopes and survive a knowledge purge.
					await db
						.delete(aclGrants)
						.where(
							and(
								or(
									eq(aclGrants.scopeType, "global"),
									eq(aclGrants.scopeType, "knowledge_collection"),
								),
								eq(aclGrants.principalType, input.principalType),
								eq(aclGrants.principalId, input.principalId),
							),
						);
				},
				{ label: "knowledge.deleteUserKnowledgeGrants" },
			);
		},

		// ── audit ──

		async insertAclAuditEvent(row: AclAuditEventWrite): Promise<void> {
			await retryKnowledgeWrite(
				async () => {
					await db.insert(aclEvents).values({
						id: row.id,
						actorUserId: row.actorUserId,
						actorRole: row.actorRole,
						eventType: row.eventType,
						subjectType: row.subjectType,
						subjectId: row.subjectId,
						scopeType: row.scopeType,
						scopeId: row.scopeId,
						outcome: row.outcome,
						detailJson: row.detailJson,
						createdAt: row.createdAt,
					});
				},
				{ label: "knowledge.insertAclAuditEvent" },
			);
		},
	};
}
