CREATE INDEX `idx_benchmark_runs_suite` ON `benchmark_runs` (`suite_id`);--> statement-breakpoint
CREATE INDEX `idx_task_results_narrator` ON `benchmark_task_results` (`narrator_id`);--> statement-breakpoint
CREATE INDEX `idx_chapters_merged_into` ON `chapters` (`merged_into_chapter_id`);--> statement-breakpoint
CREATE INDEX `idx_chapters_review_source` ON `chapters` (`review_source_chapter_id`);--> statement-breakpoint
CREATE INDEX `idx_chapters_exploration_group` ON `chapters` (`exploration_group_id`);--> statement-breakpoint
CREATE INDEX `idx_chat_group_members_user` ON `chat_group_members` (`user_id`);--> statement-breakpoint
CREATE INDEX `idx_chat_group_messages_sender_user` ON `chat_group_messages` (`sender_user_id`);--> statement-breakpoint
CREATE INDEX `idx_chat_groups_created_by` ON `chat_groups` (`created_by`);--> statement-breakpoint
CREATE INDEX `idx_device_transfer_tasks_created_by` ON `device_transfer_tasks` (`created_by`);--> statement-breakpoint
CREATE INDEX `idx_exploration_groups_base_chapter` ON `exploration_groups` (`base_chapter_id`);--> statement-breakpoint
CREATE INDEX `idx_exploration_groups_decided_chapter` ON `exploration_groups` (`decided_chapter_id`);--> statement-breakpoint
CREATE INDEX `idx_gsm_chapter` ON `gateway_session_mappings` (`chapter_id`);--> statement-breakpoint
CREATE INDEX `idx_gsm_project` ON `gateway_session_mappings` (`project_id`);--> statement-breakpoint
CREATE INDEX `idx_kc_owner_user` ON `knowledge_collections` (`owner_user_id`);--> statement-breakpoint
CREATE INDEX `idx_kd_target_collection` ON `knowledge_drafts` (`target_collection_id`);--> statement-breakpoint
CREATE INDEX `idx_ke_owner_user` ON `knowledge_entries` (`owner_user_id`);--> statement-breakpoint
CREATE INDEX `idx_kelink_created_by_user` ON `knowledge_entry_links` (`created_by_user_id`);--> statement-breakpoint
CREATE INDEX `idx_kelink_to_revision` ON `knowledge_entry_links` (`to_revision_id`);--> statement-breakpoint
CREATE INDEX `idx_kgrant_collection` ON `knowledge_grants` (`collection_id`);--> statement-breakpoint
CREATE INDEX `idx_kie_entry_revision` ON `knowledge_injection_events` (`entry_revision_id`);--> statement-breakpoint
CREATE INDEX `idx_kpack_owner_user` ON `knowledge_packs` (`owner_user_id`);--> statement-breakpoint
CREATE INDEX `idx_kr_author_user` ON `knowledge_revisions` (`author_user_id`);--> statement-breakpoint
CREATE INDEX `idx_ks_reviewer_user` ON `knowledge_submissions` (`reviewer_user_id`);--> statement-breakpoint
CREATE INDEX `idx_ks_collection` ON `knowledge_submissions` (`collection_id`);--> statement-breakpoint
CREATE INDEX `idx_ks_draft` ON `knowledge_submissions` (`draft_id`);--> statement-breakpoint
CREATE INDEX `idx_merge_sessions_target_chapter` ON `merge_sessions` (`target_chapter_id`);--> statement-breakpoint
CREATE INDEX `idx_oauth_access_tokens_revoked_by_user` ON `oauth_access_tokens` (`revoked_by_user_id`);--> statement-breakpoint
CREATE INDEX `idx_oauth_clients_created_by` ON `oauth_clients` (`created_by`);--> statement-breakpoint
CREATE INDEX `idx_oauth_clients_revoked_by_user` ON `oauth_clients` (`revoked_by_user_id`);--> statement-breakpoint
CREATE INDEX `idx_oauth_grant_events_actor_user` ON `oauth_grant_events` (`actor_user_id`);--> statement-breakpoint
CREATE INDEX `idx_oauth_grants_revoked_by_user` ON `oauth_grants` (`revoked_by_user_id`);--> statement-breakpoint
CREATE INDEX `idx_oauth_security_events_user` ON `oauth_security_events` (`user_id`);--> statement-breakpoint
CREATE INDEX `idx_oauth_security_events_grant` ON `oauth_security_events` (`grant_id`);--> statement-breakpoint
CREATE INDEX `idx_port_allocations_chapter` ON `port_allocations` (`chapter_id`);--> statement-breakpoint
CREATE INDEX `idx_scheduled_tasks_created_by` ON `scheduled_tasks` (`created_by`);--> statement-breakpoint
CREATE INDEX `idx_scheduled_tasks_reuse_narrator` ON `scheduled_tasks` (`reuse_narrator_id`);--> statement-breakpoint
CREATE INDEX `idx_scheduled_tasks_chapter` ON `scheduled_tasks` (`chapter_id`);--> statement-breakpoint
CREATE INDEX `idx_spec_protected_tasks_first_revision` ON `spec_protected_tasks` (`first_revision_id`);--> statement-breakpoint
CREATE INDEX `idx_spec_protected_tasks_last_revision` ON `spec_protected_tasks` (`last_revision_id`);--> statement-breakpoint
CREATE INDEX `idx_webauthn_challenge_user` ON `webauthn_challenges` (`user_id`);