ALTER TABLE "background_tasks" ADD COLUMN "insert_seq" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (sequence name "background_tasks_insert_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "narrator_tool_continuations" ADD COLUMN "insert_seq" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (sequence name "narrator_tool_continuations_insert_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "narrators" ADD COLUMN "next_seq" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "narrators" ADD COLUMN "insert_seq" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (sequence name "narrators_insert_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);
--> statement-breakpoint
-- Data backfill appended by scripts/finalize-postgres-seq-counter-migration.ts; do not edit by hand.
--> statement-breakpoint
UPDATE "narrators" SET "next_seq" = COALESCE((
	SELECT MAX("narrator_message_refs"."seq") + 1 FROM "narrator_message_refs"
	WHERE "narrator_message_refs"."narrator_id" = "narrators"."id"
), 0);
--> statement-breakpoint
SELECT setval(pg_get_serial_sequence('background_tasks', 'insert_seq'), COALESCE((SELECT MAX("insert_seq") FROM "background_tasks"), 0) + 1, false);
--> statement-breakpoint
SELECT setval(pg_get_serial_sequence('narrators', 'insert_seq'), COALESCE((SELECT MAX("insert_seq") FROM "narrators"), 0) + 1, false);
--> statement-breakpoint
SELECT setval(pg_get_serial_sequence('narrator_tool_continuations', 'insert_seq'), COALESCE((SELECT MAX("insert_seq") FROM "narrator_tool_continuations"), 0) + 1, false);
