/**
 * Lazy @parcel/watcher binding loader.
 *
 * This module is intentionally imported only by the watcher worker process. The
 * main NarraFork server must never load the native addon directly: native
 * subscribe hangs should be isolated to the worker process, matching VS Code's
 * file-watcher process architecture.
 */

export interface ParcelBinding {
	subscribe(
		dir: string,
		fn: (
			error: Error | null,
			events: Array<{ type: "create" | "update" | "delete"; path: string }>,
		) => void,
		opts?: Record<string, unknown>,
	): Promise<{ unsubscribe(): Promise<void> }>;
	unsubscribe(
		dir: string,
		fn: (...args: never) => unknown,
		opts?: Record<string, unknown>,
	): Promise<void>;
}

let _parcelWatcher: ParcelBinding | null | undefined; // undefined = not yet attempted

export async function getParcelWatcher(): Promise<ParcelBinding> {
	if (_parcelWatcher !== undefined) {
		if (_parcelWatcher === null) throw new Error("@parcel/watcher not available");
		return _parcelWatcher;
	}

	// Attempt 1: normal require (dev mode / non-compiled runs).
	try {
		const mod = require("@parcel/watcher") as ParcelBinding;
		_parcelWatcher = mod;
		return mod;
	} catch {
		// Expected in compiled binary — .node files are not bundled by default.
	}

	// Attempt 2: embedded binary loader generated by scripts/download-parcel-watcher.ts.
	try {
		const { loadParcelNativeBinding } = await import("@server/generated/parcel-native-loader");
		const binding = loadParcelNativeBinding();
		if (binding) {
			const { createWrapper } = require("@parcel/watcher/wrapper");
			const wrapped = createWrapper(binding) as ParcelBinding;
			_parcelWatcher = wrapped;
			return wrapped;
		}
	} catch (err) {
		throw new Error(`embedded @parcel/watcher loader failed: ${String(err)}`);
	}

	_parcelWatcher = null;
	throw new Error("@parcel/watcher not available: native binding could not be loaded");
}
