/**
 * Build script: generates embedded frontend manifest and compiles single executable.
 *
 * Usage:
 *   bun scripts/build-embedded.ts            # build frontend + compile
 *   bun scripts/build-embedded.ts --skip-frontend  # skip Vite build, reuse existing dist/frontend
 */
import { readdirSync, statSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";

const ROOT = join(import.meta.dir, "..");
const FRONTEND_DIR = join(ROOT, "dist", "frontend");
const GENERATED_FILE = join(ROOT, "server", "generated", "embedded-frontend.ts");

const skipFrontend = process.argv.includes("--skip-frontend");

// Step 1: Build frontend with Vite
if (!skipFrontend) {
	console.log("→ Building frontend...");
	const vite = Bun.spawnSync(["bunx", "vite", "build", "--config", "frontend/vite.config.ts"], {
		cwd: ROOT,
		stdio: ["inherit", "inherit", "inherit"],
	});
	if (vite.exitCode !== 0) {
		console.error("Frontend build failed");
		process.exit(1);
	}
}

// Step 2: Scan dist/frontend/ and collect all files
function walkDir(dir: string): string[] {
	const results: string[] = [];
	for (const entry of readdirSync(dir)) {
		const full = join(dir, entry);
		if (statSync(full).isDirectory()) {
			results.push(...walkDir(full));
		} else {
			results.push(full);
		}
	}
	return results;
}

const files = walkDir(FRONTEND_DIR);
const relFiles = files.map((f) => relative(ROOT, f)); // e.g. "dist/frontend/assets/index-B0dw7udb.js"

// Step 3: Generate server/generated/embedded-frontend.ts
const imports: string[] = [];
const mapEntries: string[] = [];

for (let i = 0; i < relFiles.length; i++) {
	const rel = relFiles[i];
	const urlPath = `/${relative("dist/frontend", rel)}`; // e.g. "/assets/index-B0dw7udb.js"
	const importPath = `../../${rel}`; // relative from server/generated/ to project root

	imports.push(`import _f${i} from ${JSON.stringify(importPath)} with { type: "file" };`);
	mapEntries.push(`\t${JSON.stringify(urlPath)}: _f${i},`);
}

const code = `// AUTO-GENERATED by scripts/build-embedded.ts — DO NOT EDIT
${imports.join("\n")}

/** URL path → embedded file path (resolved at compile time via $bunfs) */
export const embeddedAssets: Record<string, string> = {
${mapEntries.join("\n")}
};
`;

writeFileSync(GENERATED_FILE, code);
console.log(`→ Generated ${relative(ROOT, GENERATED_FILE)} (${relFiles.length} files)`);

// Step 4: Compile single executable
console.log("→ Compiling executable...");
const compile = Bun.spawnSync(
	[
		"bun",
		"build",
		"./server/index.ts",
		"--compile",
		"--minify",
		"--asset-naming=[dir]/[name].[ext]",
		"--outfile=./dist/narrafork",
	],
	{
		cwd: ROOT,
		stdio: ["inherit", "inherit", "inherit"],
	},
);
if (compile.exitCode !== 0) {
	console.error("Compilation failed");
	process.exit(1);
}

console.log("→ Done! Executable: dist/narrafork");
