/**
 * Build script: generates embedded asset manifests and compiles single executable.
 *
 * Usage:
 *   bun scripts/build-embedded.ts                   # build frontend + compile
 *   bun scripts/build-embedded.ts --skip-frontend   # skip Vite build, reuse dist/frontend
 */
import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";

const ROOT = join(import.meta.dir, "..");
const FRONTEND_DIR = join(ROOT, "dist", "frontend");
const DRIZZLE_DIR = join(ROOT, "drizzle");
const DRIZZLE_JOURNAL_PATH = join(DRIZZLE_DIR, "meta", "_journal.json");

const GENERATED_FRONTEND_FILE = join(ROOT, "server", "generated", "embedded-frontend.ts");
const GENERATED_MIGRATIONS_DATA_FILE = join(
	ROOT,
	"server",
	"generated",
	"embedded-migrations-data.ts",
);

const skipFrontend = process.argv.includes("--skip-frontend");

function walkDir(dir: string): string[] {
	const results: string[] = [];
	for (const entry of readdirSync(dir)) {
		const full = join(dir, entry);
		if (statSync(full).isDirectory()) {
			results.push(...walkDir(full));
		} else {
			results.push(full);
		}
	}
	return results;
}

function generateEmbeddedFrontendManifest() {
	if (!existsSync(FRONTEND_DIR)) {
		console.error(`Frontend build output not found: ${relative(ROOT, FRONTEND_DIR)}`);
		process.exit(1);
	}

	const files = walkDir(FRONTEND_DIR);
	const relFiles = files.map((f) => relative(ROOT, f));

	const imports: string[] = [];
	const mapEntries: string[] = [];

	for (let i = 0; i < relFiles.length; i++) {
		const rel = relFiles[i];
		const urlPath = `/${relative("dist/frontend", rel)}`;
		const importPath = `../../${rel}`;

		imports.push(`import _f${i} from ${JSON.stringify(importPath)} with { type: "file" };`);
		mapEntries.push(`\t${JSON.stringify(urlPath)}: _f${i},`);
	}

	const code = `// AUTO-GENERATED by scripts/build-embedded.ts — DO NOT EDIT
${imports.join("\n")}

/** URL path → embedded file path (resolved at compile time via $bunfs) */
export const embeddedAssets: Record<string, string> = {
${mapEntries.join("\n")}
};
`;

	writeFileSync(GENERATED_FRONTEND_FILE, code);
	console.log(`→ Generated ${relative(ROOT, GENERATED_FRONTEND_FILE)} (${relFiles.length} files)`);
}

type DrizzleJournal = {
	entries: Array<{
		tag: string;
	}>;
};

function generateEmbeddedMigrationsDataModule() {
	if (!existsSync(DRIZZLE_JOURNAL_PATH)) {
		console.error(`Drizzle migration journal not found: ${relative(ROOT, DRIZZLE_JOURNAL_PATH)}`);
		console.error("Run `bun run db:generate` first, then re-run build:compile.");
		process.exit(1);
	}

	const journalJson = readFileSync(DRIZZLE_JOURNAL_PATH, "utf-8");
	const journal = JSON.parse(journalJson) as DrizzleJournal;
	const sqlFiles = journal.entries.map((entry) => {
		const fileName = `${entry.tag}.sql`;
		const filePath = join(DRIZZLE_DIR, fileName);
		if (!existsSync(filePath)) {
			console.error(`Drizzle migration SQL file missing: ${relative(ROOT, filePath)}`);
			process.exit(1);
		}
		return {
			name: fileName,
			content: readFileSync(filePath, "utf-8"),
		};
	});

	const sqlEntries = sqlFiles
		.map(
			(file) =>
				`\t{ name: ${JSON.stringify(file.name)}, content: ${JSON.stringify(file.content)} },`,
		)
		.join("\n");

	const code = `// AUTO-GENERATED by scripts/build-embedded.ts — DO NOT EDIT
export const embeddedMigrationJournalJson = ${JSON.stringify(journalJson)};

export const embeddedMigrationSqlFiles: ReadonlyArray<{ name: string; content: string }> = [
${sqlEntries}
];
`;

	writeFileSync(GENERATED_MIGRATIONS_DATA_FILE, code);
	console.log(
		`→ Generated ${relative(ROOT, GENERATED_MIGRATIONS_DATA_FILE)} (${sqlFiles.length} migrations)`,
	);
}

// Step 1: Build frontend with Vite
if (!skipFrontend) {
	console.log("→ Building frontend...");
	const vite = Bun.spawnSync(["bunx", "vite", "build", "--config", "frontend/vite.config.ts"], {
		cwd: ROOT,
		stdio: ["inherit", "inherit", "inherit"],
	});
	if (vite.exitCode !== 0) {
		console.error("Frontend build failed");
		process.exit(1);
	}
}

// Step 2: Generate embedded frontend manifest
console.log("→ Generating embedded frontend manifest...");
generateEmbeddedFrontendManifest();

// Step 3: Generate embedded migration data module
console.log("→ Generating embedded migration data module...");
generateEmbeddedMigrationsDataModule();

// Step 4: Compile single executable
console.log("→ Compiling executable...");
const compile = Bun.spawnSync(
	[
		"bun",
		"build",
		"./server/index.ts",
		"--compile",
		"--minify",
		"--asset-naming=[dir]/[name].[ext]",
		"--outfile=./dist/narrafork",
	],
	{
		cwd: ROOT,
		stdio: ["inherit", "inherit", "inherit"],
	},
);
if (compile.exitCode !== 0) {
	console.error("Compilation failed");
	process.exit(1);
}

console.log("→ Done! Executable: dist/narrafork");
