/**
 * Download @parcel/watcher native binaries for all target platforms.
 *
 * Fetches platform-specific npm packages, extracts `watcher.node` files,
 * and places them in `server/generated/parcel-watcher-binaries/`.
 *
 * Also generates `server/generated/parcel-native-loader.ts` which embeds
 * the binaries via `import ... with { type: "file" }` for Bun --compile.
 *
 * Usage:
 *   bun scripts/download-parcel-watcher.ts
 */
import { createHash, randomUUID } from "node:crypto";
import {
	existsSync,
	lstatSync,
	mkdirSync,
	readFileSync,
	renameSync,
	rmSync,
	writeFileSync,
} from "node:fs";
import { join } from "node:path";
import {
	downloadWatcher,
	lockedWatcherIdentity,
	nativeTarget,
	validateNativeBytes,
	WATCHER_PACKAGES,
	watcherCacheMatches,
} from "./lib/ci-build-native";

const ROOT = join(import.meta.dir, "..");
const OUT_DIR = join(ROOT, "server", "generated", "parcel-watcher-binaries");
const LOADER_FILE = join(ROOT, "server", "generated", "parcel-native-loader.ts");

// Read version from installed @parcel/watcher
const parcelPkg = JSON.parse(
	readFileSync(join(ROOT, "node_modules", "@parcel", "watcher", "package.json"), "utf-8"),
);
const PARCEL_VERSION: string = parcelPkg.version;

/**
 * Platform mapping: our build target suffix → @parcel/watcher package name.
 *
 * Key = identifier used in generated loader (also matches Bun compile targets).
 * Value = npm package name containing the `watcher.node` binary.
 */
const requestedTargets = process.argv
	.slice(2)
	.filter((arg) => arg.startsWith("--target="))
	.map((arg) => arg.slice("--target=".length));
const selectedKeys = requestedTargets.length
	? [...new Set(requestedTargets.map((target) => nativeTarget(target).watcher))]
	: Object.keys(WATCHER_PACKAGES);
const PLATFORMS = Object.fromEntries(selectedKeys.map((key) => [key, WATCHER_PACKAGES[key]]));
const lock = readFileSync(join(ROOT, "bun.lock"), "utf8");
// Validate the installed watcher itself, not just the platform tarballs.
lockedWatcherIdentity(lock, "@parcel/watcher", PARCEL_VERSION);

// ── Download helpers ────────────────────────────────────────────────────────

async function downloadAndExtract(key: string, pkgName: string, outPath: string): Promise<void> {
	const integrity = lockedWatcherIdentity(lock, pkgName, PARCEL_VERSION);
	if (await watcherCacheMatches(outPath, key, pkgName, PARCEL_VERSION, integrity)) {
		console.log(`  Cached native binary verified: ${key}`);
		return;
	}
	console.log(`  Downloading ${pkgName}@${PARCEL_VERSION}`);
	let tarball: Uint8Array | undefined;
	const nodeFile = await downloadWatcher(
		pkgName,
		PARCEL_VERSION,
		integrity,
		undefined,
		undefined,
		(bytes) => {
			tarball = bytes;
		},
	);
	validateNativeBytes(nodeFile, key);
	if (!tarball) throw new Error("Missing verified watcher tarball");
	const temporary = `${outPath}.${randomUUID()}.tmp`;
	try {
		writeFileSync(temporary, nodeFile, { flag: "wx" });
		renameSync(temporary, outPath);
		writeFileSync(temporary, tarball, { flag: "wx" });
		renameSync(temporary, `${outPath}.tgz`);
		writeFileSync(
			temporary,
			JSON.stringify({
				name: pkgName,
				version: PARCEL_VERSION,
				integrity,
				sha256: createHash("sha256").update(nodeFile).digest("hex"),
			}),
			{ flag: "wx" },
		);
		renameSync(temporary, `${outPath}.json`);
	} finally {
		rmSync(temporary, { force: true });
	}
	console.log(`  Verified ${key} (${nodeFile.length} bytes)`);
}

// ── Main ────────────────────────────────────────────────────────────────────

if (!existsSync(OUT_DIR)) {
	mkdirSync(OUT_DIR, { recursive: true });
}

console.log(`Downloading @parcel/watcher v${PARCEL_VERSION} native binaries...\n`);

if (!lstatSync(OUT_DIR).isDirectory() || lstatSync(OUT_DIR).isSymbolicLink()) {
	throw new Error("Watcher cache must be a real directory");
}
const succeeded: Array<{ key: string }> = [];
for (const [key, pkgName] of Object.entries(PLATFORMS)) {
	const outPath = join(OUT_DIR, `watcher-${key}.node`);
	// A missing required dependency must never produce a partial loader.
	await downloadAndExtract(key, pkgName, outPath);
	succeeded.push({ key });
}
console.log(`\nVerified ${succeeded.length}/${selectedKeys.length} platform binaries`);

// ── Generate loader file ────────────────────────────────────────────────────

console.log("\n→ Generating parcel-native-loader.ts...");

/**
 * Runtime platform detection → loader key mapping.
 *
 * At runtime we check process.platform + process.arch (+ libc on Linux)
 * to pick the right embedded binary.
 */
const loaderCode = `// @ts-nocheck — generated file with Bun-specific import attributes
// AUTO-GENERATED by scripts/download-parcel-watcher.ts — DO NOT EDIT
//
// Embeds @parcel/watcher v${PARCEL_VERSION} native binaries for all platforms.
// At runtime, extracts the correct binary to disk and loads it via process.dlopen.

import { existsSync, mkdirSync, writeFileSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { homedir } from "node:os";

// Embed all platform binaries via Bun's file embedding
${succeeded.map((r) => `import _${r.key.replace(/-/g, "_")} from "./parcel-watcher-binaries/watcher-${r.key}.node" with { type: "file" };`).join("\n")}

const EMBEDDED: Record<string, string> = {
${succeeded.map((r) => `\t"${r.key}": _${r.key.replace(/-/g, "_")},`).join("\n")}
};

const PARCEL_VERSION = ${JSON.stringify(PARCEL_VERSION)};

/**
 * Detect the current platform key for @parcel/watcher binary selection.
 */
function detectPlatformKey(): string | null {
\tconst platform = process.platform;
\tconst arch = process.arch as string;

\tif (platform === "darwin") {
\t\treturn arch === "arm64" ? "darwin-arm64" : "darwin-x64";
\t}

\tif (platform === "win32") {
\t\treturn arch === "arm64" ? "win32-arm64" : "win32-x64";
\t}

\tif (platform === "linux") {
\t\t// Detect musl vs glibc
\t\tlet isMusl = false;
\t\ttry {
\t\t\t// Check if we're running on musl by looking at the dynamic linker
\t\t\tconst lddOutput = require("node:child_process")
\t\t\t\t.execSync("ldd --version 2>&1 || true", { encoding: "utf-8" });
\t\t\tisMusl = lddOutput.toLowerCase().includes("musl");
\t\t} catch {
\t\t\t// Default to glibc
\t\t}
\t\tconst libc = isMusl ? "musl" : "glibc";
\t\tif (arch === "arm64" || arch === "aarch64") {
\t\t\treturn \`linux-arm64-\${libc}\`;
\t\t}
\t\treturn \`linux-x64-\${libc}\`;
\t}

\treturn null;
}

/**
 * Load the @parcel/watcher native binding for the current platform.
 *
 * In compiled binary mode, extracts the embedded .node file to
 * ~/.narrafork/cache/ and loads it via process.dlopen.
 *
 * Returns the raw binding object (same as require("@parcel/watcher-xxx")).
 */
export function loadParcelNativeBinding(): Record<string, (...args: unknown[]) => unknown> | null {
\tconst key = detectPlatformKey();
\tif (!key) return null;

\tconst embeddedPath = EMBEDDED[key];
\tif (!embeddedPath) return null;

\t// Extract to a stable cache path so we don't re-extract on every startup
\tconst cacheDir = join(homedir(), ".narrafork", "cache");
\tconst cachePath = join(cacheDir, \`parcel-watcher-\${PARCEL_VERSION}-\${key}.node\`);

\tif (!existsSync(cachePath)) {
\t\tif (!existsSync(cacheDir)) {
\t\t\tmkdirSync(cacheDir, { recursive: true });
\t\t}
\t\t// Read from $bunfs embedded path and write to disk
\t\tconst data = readFileSync(embeddedPath);
\t\twriteFileSync(cachePath, data);
\t}

\t// Load via process.dlopen
\tconst mod: { exports: Record<string, (...args: unknown[]) => unknown> } = { exports: {} };
\ttry {
\t\tprocess.dlopen(mod, cachePath);
\t\treturn mod.exports;
\t} catch (err) {
\t\tconsole.error(\`Failed to load parcel watcher native binding from \${cachePath}:\`, err);
\t\treturn null;
\t}
}
`;

writeFileSync(LOADER_FILE, loaderCode);
console.log(`✓ Generated ${LOADER_FILE}`);
