import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { loadManifest } from "./check-postgres-schema-parity";
import { PG_ONLY_IDENTITY_COLUMNS } from "./generate-postgres-schema";

/**
 * Finalize the seq-counter migration batch (drizzle-postgres 0001).
 *
 * `drizzle-kit generate` emits schema DDL only; it cannot know that
 * `narrators.next_seq` must be backfilled from `narrator_message_refs` or that the
 * identity sequences behind the three `insert_seq` columns must be parked above the
 * rows PostgreSQL just numbered. Those data statements are derived here — from the
 * same {@link PG_ONLY_IDENTITY_COLUMNS} single source the schema overlay uses — and
 * appended to the freshly generated migration by THIS script, never by hand. The
 * script refuses to run against anything but the exact expected diff, so the file on
 * disk stays byte-predictable: pure drizzle-kit output plus this block.
 *
 * Flow: bun scripts/generate-postgres-schema.ts
 *       bunx drizzle-kit generate --config drizzle.pg.config.ts --name seq_counters
 *       bun scripts/finalize-postgres-seq-counter-migration.ts
 */

/**
 * The backfill for `narrators.next_seq`, per the frozen design in
 * `server/services/narrator-refs/seq-store.ts` ("SCHEMA PROPOSAL"): the next claimable
 * seq is one past the narrator's current top-of-history ref, or 0 when it has none —
 * NARRATOR_REF_SEQ_BASE. New narrators get the column DEFAULT 0 and need no row here.
 */
export const NEXT_SEQ_BACKFILL_SQL = `UPDATE "narrators" SET "next_seq" = COALESCE((
	SELECT MAX("narrator_message_refs"."seq") + 1 FROM "narrator_message_refs"
	WHERE "narrator_message_refs"."narrator_id" = "narrators"."id"
), 0);`;

/**
 * Park each identity sequence so the next allocated value is `MAX(insert_seq) + 1`.
 *
 * `ALTER TABLE … ADD COLUMN … GENERATED BY DEFAULT AS IDENTITY` already numbers every
 * existing row 1..N and leaves the sequence there, so on a PG-native database this is
 * a no-op rewrite of the same position. It exists for the SQLite→PG data migration:
 * explicit `insert_seq` INSERTs (the rowid backfill BY DEFAULT exists for) do NOT
 * advance the sequence, and this statement is what guarantees post-migration inserts
 * allocate strictly above the backfilled top. `is_called = false` makes the next
 * `nextval` return exactly the given value: max+1 on a populated table, 1 on an empty
 * one (where `COALESCE` keeps `setval` off the NULL it rejects). Idempotent.
 */
export function identitySetvalSql(table: string, column: string): string {
	return (
		`SELECT setval(pg_get_serial_sequence('${table}', '${column}'), ` +
		`COALESCE((SELECT MAX("${column}") FROM "${table}"), 0) + 1, false);`
	);
}

/** The complete data block, in a fixed order, derived from the overlay single source. */
export function seqCounterBackfillStatements(): string[] {
	const manifest = loadManifest();
	const physical = new Map(manifest.tables.map((table) => [table.exportName, table.name]));
	const nextSeq = manifest.tables
		.find((table) => table.name === "narrators")
		?.columns.find((column) => column.name === "next_seq");
	if (
		!nextSeq ||
		nextSeq.pgType !== "integer" ||
		!nextSeq.notNull ||
		nextSeq.defaultExpression !== "0"
	) {
		throw new Error(
			"manifest narrators.next_seq is not `integer NOT NULL DEFAULT 0`; refusing to backfill an unexpected shape",
		);
	}
	const statements = [NEXT_SEQ_BACKFILL_SQL];
	for (const overlay of PG_ONLY_IDENTITY_COLUMNS) {
		const table = physical.get(overlay.table);
		if (!table) throw new Error(`manifest is missing overlay table ${overlay.table}`);
		const column = manifest.tables
			.find((entry) => entry.name === table)
			?.columns.find((entry) => entry.name === overlay.name);
		if (column?.identity?.type !== "byDefault" || column.pgType !== "bigint") {
			throw new Error(
				`manifest ${table}.${overlay.name} is not a BY DEFAULT bigint identity column`,
			);
		}
		statements.push(identitySetvalSql(table, overlay.name));
	}
	return statements;
}

/** Marker so re-running is a verifiable no-op rather than a double append. */
export const BACKFILL_BLOCK_MARKER =
	"-- Data backfill appended by scripts/finalize-postgres-seq-counter-migration.ts; do not edit by hand.";

export function appendBackfillBlock(sql: string, statements: string[]): string {
	const marker = sql.indexOf(BACKFILL_BLOCK_MARKER);
	if (marker >= 0) {
		const expected = appendBackfillBlock(sql.slice(0, marker), statements);
		if (expected !== sql)
			throw new Error("existing migration backfill differs; refusing to rewrite history");
		return sql;
	}
	const separator = "--> statement-breakpoint";
	const tail = sql.trimEnd();
	if (!tail.endsWith(separator) && !tail.endsWith(";")) {
		throw new Error("migration SQL does not end with a statement or breakpoint");
	}
	const block = [BACKFILL_BLOCK_MARKER, ...statements].join(`\n${separator}\n`);
	const needsSeparator = !tail.endsWith(separator);
	return `${tail}${needsSeparator ? `\n${separator}` : ""}\n${block}\n`;
}

if (import.meta.main) {
	const root = resolve(import.meta.dir, "..");
	const journal = JSON.parse(
		readFileSync(resolve(root, "drizzle-postgres/meta/_journal.json"), "utf8"),
	) as { entries: { tag: string }[] };
	const tag = process.argv[2] ?? journal.entries.at(-1)?.tag;
	if (!tag) throw new Error("no PostgreSQL migration to finalize");
	if (tag !== "0001_seq_counters" || !journal.entries.some((entry) => entry.tag === tag)) {
		throw new Error(`migration ${tag} is not the journaled seq-counter batch`);
	}
	const file = resolve(root, `drizzle-postgres/${tag}.sql`);
	const sql = readFileSync(file, "utf8");

	// The DDL half of this batch is exactly these four ADD COLUMNs — nothing else may
	// ride along, or the backfill would be attached to a diff nobody reviewed.
	const adds = sql
		.split(BACKFILL_BLOCK_MARKER)[0]
		.split("--> statement-breakpoint")
		.map((statement) => statement.trim())
		.filter(Boolean)
		.map((statement) => {
			const match = /^ALTER TABLE "(\w+)" ADD COLUMN "(\w+)" ([^;]+);$/.exec(statement);
			if (!match) throw new Error("unexpected statement in generated DDL; refusing to finalize");
			return `${match[1]}.${match[2]}: ${match[3].replace(/\s+/g, " ").trim()}`;
		});
	const expected = [
		'background_tasks.insert_seq: bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (sequence name "background_tasks_insert_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1)',
		'narrator_tool_continuations.insert_seq: bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (sequence name "narrator_tool_continuations_insert_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1)',
		"narrators.next_seq: integer DEFAULT 0 NOT NULL",
		'narrators.insert_seq: bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (sequence name "narrators_insert_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1)',
	];
	if (adds.length !== expected.length || !expected.every((item) => adds.includes(item))) {
		throw new Error(`unexpected migration diff (${adds.length} ADD COLUMNs):\n${adds.join("\n")}`);
	}

	const statements = seqCounterBackfillStatements();
	const finalized = appendBackfillBlock(sql, statements);
	if (finalized === sql) {
		console.log(JSON.stringify({ tag, changed: false, statements: statements.length }));
	} else {
		writeFileSync(file, finalized);
		console.log(
			JSON.stringify({
				tag,
				changed: true,
				statements: statements.length,
				sha256: createHash("sha256").update(finalized).digest("hex"),
			}),
		);
	}
}
