import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

interface DrizzleJournalEntry {
	idx: number;
	when: number;
	tag: string;
}

interface DrizzleJournal {
	entries: DrizzleJournalEntry[];
}

interface EmbeddedMigration {
	tag: string;
	when: number;
	hash: string;
	sql: string;
}

const repoRoot = path.resolve(import.meta.dir, "..");
const journalPath = path.join(repoRoot, "drizzle", "meta", "_journal.json");
const outputPath = path.join(
	repoRoot,
	"go_backend",
	"internal",
	"db",
	"drizzle_migrations_embedded.go",
);
const journalArtifactPath = path.join(
	repoRoot,
	"go_backend",
	"compat",
	"bun-final",
	"db",
	"drizzle_journal_snapshot.json",
);

const journal = JSON.parse(await readFile(journalPath, "utf8")) as DrizzleJournal;
if (!Array.isArray(journal.entries)) {
	throw new Error(`${journalPath} does not contain an entries array`);
}

const migrations: EmbeddedMigration[] = [];
for (const [index, entry] of journal.entries.entries()) {
	if (entry.idx !== index) {
		throw new Error(`journal entry ${entry.tag} has idx ${entry.idx}, want ${index}`);
	}
	if (!entry.tag || !Number.isSafeInteger(entry.when)) {
		throw new Error(`journal entry at index ${index} is missing a valid tag/when`);
	}

	const sqlPath = path.join(repoRoot, "drizzle", `${entry.tag}.sql`);
	const sqlBytes = await readFile(sqlPath);
	migrations.push({
		tag: entry.tag,
		when: entry.when,
		hash: createHash("sha256").update(sqlBytes).digest("hex"),
		sql: sqlBytes.toString("utf8"),
	});
}

const content = generateGoFile(migrations);
await mkdir(path.dirname(outputPath), { recursive: true });
await writeFile(outputPath, content);

const journalArtifact = generateJournalArtifact(journal, migrations);
await mkdir(path.dirname(journalArtifactPath), { recursive: true });
await writeFile(journalArtifactPath, `${JSON.stringify(journalArtifact, null, "\t")}\n`);

const gofmt = Bun.spawnSync(["gofmt", "-w", outputPath], {
	cwd: repoRoot,
	stderr: "pipe",
	stdout: "pipe",
});
if (!gofmt.success) {
	throw new Error(`gofmt failed: ${gofmt.stderr.toString()}`);
}

console.log(
	`Generated ${path.relative(repoRoot, outputPath)} with ${migrations.length} migrations`,
);
console.log(`Generated ${path.relative(repoRoot, journalArtifactPath)}`);

function generateJournalArtifact(journal: DrizzleJournal, migrations: EmbeddedMigration[]) {
	const snapshotEntries = migrations.map((migration) => ({
		Tag: migration.tag,
		When: migration.when,
		Hash: migration.hash,
	}));
	return {
		version: "1",
		dialect: "sqlite",
		drizzleJournalVersion: String((journal as { version?: string }).version ?? ""),
		lastTag: migrations.at(-1)?.tag ?? "",
		expectedMigrationCount: migrations.length,
		expectedJournalHash: createHash("sha256").update(JSON.stringify(snapshotEntries)).digest("hex"),
		entries: migrations.map((migration, index) => ({
			idx: index,
			tag: migration.tag,
			when: migration.when,
			hash: migration.hash,
		})),
	};
}

function generateGoFile(migrations: EmbeddedMigration[]): string {
	const lines = [
		"// Code generated by scripts/generate-go-drizzle-migrations.ts; DO NOT EDIT.",
		"",
		"package db",
		"",
		"type embeddedDrizzleMigration struct {",
		"\tTag string",
		"\tWhen int64",
		"\tHash string",
		"\tSQL string",
		"}",
		"",
		"var embeddedDrizzleMigrations = []embeddedDrizzleMigration{",
	];

	for (const migration of migrations) {
		lines.push("\t{");
		lines.push(`\t\tTag:  ${goQuote(migration.tag)},`);
		lines.push(`\t\tWhen: ${migration.when},`);
		lines.push(`\t\tHash: ${goQuote(migration.hash)},`);
		lines.push(`\t\tSQL:  ${goMultilineString(migration.sql, "\t\t\t")},`);
		lines.push("\t},");
	}

	lines.push(
		"}",
		"",
		"func init() {",
		"\tembeddedDrizzleMigrationSnapshot = deriveEmbeddedDrizzleMigrationSnapshot(embeddedDrizzleMigrations)",
		"}",
		"",
		"func deriveEmbeddedDrizzleMigrationSnapshot(migrations []embeddedDrizzleMigration) []drizzleMigrationSnapshotEntry {",
		"\tsnapshot := make([]drizzleMigrationSnapshotEntry, 0, len(migrations))",
		"\tfor _, migration := range migrations {",
		"\t\tsnapshot = append(snapshot, drizzleMigrationSnapshotEntry{",
		"\t\t\tTag:  migration.Tag,",
		"\t\t\tWhen: migration.When,",
		"\t\t\tHash: migration.Hash,",
		"\t\t})",
		"\t}",
		"\treturn snapshot",
		"}",
		"",
	);

	return `${lines.join("\n")}`;
}

function goMultilineString(value: string, indent: string): string {
	if (value.length === 0) {
		return goQuote("");
	}

	const chunks = chunkString(value, 1024);
	if (chunks.length === 1) {
		return goQuote(chunks[0]);
	}

	return ['""', ...chunks.map((chunk) => `${indent}${goQuote(chunk)}`)].join(" +\n");
}

function chunkString(value: string, chunkSize: number): string[] {
	const chunks: string[] = [];
	for (let index = 0; index < value.length; index += chunkSize) {
		chunks.push(value.slice(index, index + chunkSize));
	}
	return chunks;
}

function goQuote(value: string): string {
	return JSON.stringify(value)
		.replace(/</g, "\\u003c")
		.replace(/>/g, "\\u003e")
		.replace(/&/g, "\\u0026");
}
