import { execSync } from "node:child_process";
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { resolve } from "node:path";
import { eq } from "drizzle-orm";
import { db } from "../db";
import { chapters, containerInstances } from "../db/schema";
import { ContainerError, NotFoundError, PodmanNotFoundError, ValidationError } from "../lib/errors";
import { eventBus } from "../lib/event-bus";
import { generateId } from "../lib/id";
import { logger } from "../lib/logger";
import { type PortMapping, portAllocator } from "./port-allocator";

export interface ContainerConfig {
	composeFile?: string;
	services?: string[];
	ports?: Array<{ containerPort: number; serviceName: string }>;
	env?: Record<string, string>;
}

interface ExecResult {
	stdout: string;
	stderr: string;
	exitCode: number;
}

/** Check if podman is available. Throws PodmanNotFoundError if not. Cached after first success. */
let _verified = false;
let _verifyPromise: Promise<void> | null = null;

async function ensurePodman(): Promise<void> {
	if (_verified) return;
	if (_verifyPromise) return _verifyPromise;
	_verifyPromise = doEnsurePodman();
	try {
		await _verifyPromise;
	} finally {
		_verifyPromise = null;
	}
}

async function doEnsurePodman(): Promise<void> {
	try {
		execSync("podman --version", { encoding: "utf-8", stdio: "pipe", timeout: 5000 });
		ensureCgroupConfig();
		await ensurePodmanSocket();
		_verified = true;
		logger.info("Container runtime detected", { runtime: "podman" });
	} catch (err) {
		if (err instanceof PodmanNotFoundError) throw err;
		throw new PodmanNotFoundError();
	}
}

/**
 * On Linux without a systemd user session, podman defaults to cgroup_manager=systemd
 * which spams warnings and can fail. Detect this and write a user-level containers.conf
 * to use cgroupfs instead.
 */
function ensureCgroupConfig(): void {
	if (process.platform !== "linux") return;

	// Check if systemd user session is available
	try {
		execSync("systemctl --user is-system-running", {
			encoding: "utf-8",
			stdio: "pipe",
			timeout: 3000,
		});
		return; // systemd session works, no fix needed
	} catch {
		// No systemd user session
	}

	// Check current cgroup manager
	try {
		const mgr = execSync("podman info --format '{{.Host.CgroupManager}}'", {
			encoding: "utf-8",
			stdio: "pipe",
			timeout: 5000,
		}).trim();
		if (mgr === "cgroupfs") return; // Already using cgroupfs
	} catch {
		// Can't determine — try to fix anyway
	}

	// Write user-level containers.conf to force cgroupfs
	const confDir = resolve(homedir(), ".config", "containers");
	const confPath = resolve(confDir, "containers.conf");
	if (existsSync(confPath)) return; // Don't overwrite existing config

	try {
		mkdirSync(confDir, { recursive: true });
		writeFileSync(
			confPath,
			[
				"# Auto-generated by NarraFork — no systemd user session detected",
				"[engine]",
				'cgroup_manager = "cgroupfs"',
				'events_logger = "file"',
				"",
			].join("\n"),
		);
		logger.info("Created containers.conf with cgroupfs manager", { path: confPath });
	} catch (err) {
		logger.warn("Failed to create containers.conf", { error: String(err) });
	}
}

/**
 * Ensure the podman API socket is running. `podman compose` delegates to
 * docker-compose which connects via the socket. Without it every compose
 * command fails with "Cannot connect to the Docker daemon".
 */
async function ensurePodmanSocket(): Promise<void> {
	// Determine the expected socket path
	let socketPath: string | undefined;
	try {
		socketPath = execSync("podman info --format '{{.Host.RemoteSocket.Path}}'", {
			encoding: "utf-8",
			stdio: "pipe",
			timeout: 5000,
		}).trim();
	} catch {
		// Fallback: common default
		const uid = process.getuid?.() ?? 1000;
		socketPath = `/tmp/storage-run-${uid}/podman/podman.sock`;
	}

	if (socketPath && existsSync(socketPath)) return; // Socket already exists

	// Start the socket service. Try systemd first, fall back to manual.
	try {
		execSync("systemctl --user start podman.socket", {
			encoding: "utf-8",
			stdio: "pipe",
			timeout: 10000,
		});
		logger.info("Started podman socket via systemd");
		return;
	} catch {
		// systemd not available or unit missing
	}

	// Manual: launch podman system service in the background (timeout=0 = run forever)
	try {
		const proc = Bun.spawn(["podman", "system", "service", "--time=0"], {
			stdout: "ignore",
			stderr: "ignore",
		});
		// Detach — we don't await this process
		proc.unref();
		// Wait for socket to appear (up to 5s)
		for (let i = 0; i < 50; i++) {
			if (socketPath && existsSync(socketPath)) break;
			await Bun.sleep(100);
		}
		logger.info("Started podman system service in background", { pid: proc.pid });
	} catch (err) {
		logger.warn("Failed to start podman system service", { error: String(err) });
	}
}

/** Reset the cached podman check (used after installation). */
export function resetPodmanCache(): void {
	_verified = false;
}

/** Return podman status: installed + version, or not installed. */
export function getPodmanStatus(): { installed: boolean; version?: string } {
	try {
		const out = execSync("podman --version", {
			encoding: "utf-8",
			stdio: "pipe",
			timeout: 5000,
		}).trim();
		_verified = true;
		return { installed: true, version: out };
	} catch {
		return { installed: false };
	}
}

async function exec(
	args: string[],
	cwd: string,
	env?: Record<string, string>,
): Promise<ExecResult> {
	await ensurePodman();
	const proc = Bun.spawn(["podman", ...args], {
		cwd,
		stdout: "pipe",
		stderr: "pipe",
		env: { ...process.env, ...env },
	});
	const [stdout, rawStderr] = await Promise.all([
		new Response(proc.stdout).text(),
		new Response(proc.stderr).text(),
	]);
	const exitCode = await proc.exited;
	// Strip ANSI escape codes, then filter podman noise
	// biome-ignore lint/suspicious/noControlCharactersInRegex: stripping ANSI escape sequences
	const cleaned = rawStderr.replace(/\x1b\[[0-9;]*m/g, "");
	const stderr = cleaned
		.split("\n")
		.filter(
			(line) =>
				line.trim() !== "" &&
				!line.includes("cgroupv2 manager is set to systemd") &&
				!line.includes("you may need to log in using a user session") &&
				!line.includes("enable lingering with") &&
				!line.includes("Falling back to --cgroup-manager") &&
				!line.includes("Executing external compose provider") &&
				!line.includes("podman-compose(1) for how to disable"),
		)
		.join("\n")
		.trim();
	if (exitCode !== 0) {
		logger.error("Container command failed", {
			cmd: ["podman", ...args].join(" "),
			cwd,
			stderr,
			exitCode,
		});
	}
	return { stdout: stdout.trim(), stderr, exitCode };
}

/** Resolve the compose file path in a worktree directory. */
export function resolveComposeFile(
	worktreePath: string,
	config: ContainerConfig | null,
): string | null {
	if (config?.composeFile) {
		const p = resolve(worktreePath, config.composeFile);
		// Prevent path traversal — resolved path must stay within worktree
		if (!p.startsWith(`${worktreePath}/`) && p !== worktreePath) return null;
		return existsSync(p) ? p : null;
	}
	for (const name of ["compose.yml", "compose.yaml"]) {
		const p = resolve(worktreePath, name);
		if (existsSync(p)) return p;
	}
	return null;
}

/** Build environment variables for compose, including port mappings. */
export function buildComposeEnv(
	chapterId: string,
	portMappings: PortMapping[],
	config: ContainerConfig | null,
): Record<string, string> {
	const env: Record<string, string> = {
		NARRAFORK_CHAPTER_ID: chapterId,
		NARRAFORK_VOLUME_PREFIX: `nf_${chapterId.slice(0, 12)}`,
	};
	for (const { hostPort, containerPort } of portMappings) {
		env[`PORT_${containerPort}`] = String(hostPort);
	}
	if (config?.env) {
		Object.assign(env, config.env);
	}
	return env;
}

export const containerService = {
	/**
	 * Start containers for a chapter based on its containerConfig.
	 * Allocates ports, runs compose up, records container instances.
	 */
	async startChapterContainers(chapterId: string): Promise<void> {
		const chapter = await db.query.chapters.findFirst({ where: eq(chapters.id, chapterId) });
		if (!chapter) throw new NotFoundError("Chapter", chapterId);
		if (!chapter.worktreePath) throw new ValidationError("Chapter has no worktree");

		const config = chapter.containerConfig as ContainerConfig | null;
		const composeFile = resolveComposeFile(chapter.worktreePath, config);
		if (!composeFile) {
			logger.debug("No compose file found, skipping container start", { chapterId });
			return;
		}

		// Allocate ports
		let portMappings: PortMapping[] = [];
		if (config?.ports && config.ports.length > 0) {
			portMappings = await portAllocator.allocate(chapterId, config.ports);
		}

		const env = buildComposeEnv(chapterId, portMappings, config);

		// Build compose args
		const composeArgs = ["compose", "-f", composeFile, "up", "-d"];
		if (config?.services && config.services.length > 0) {
			composeArgs.push(...config.services);
		}

		const result = await exec(composeArgs, chapter.worktreePath, env);
		if (result.exitCode !== 0) {
			// Cleanup allocated ports on failure
			await portAllocator.release(chapterId);
			throw new ContainerError(
				result.stderr || `compose up failed with exit code ${result.exitCode}`,
			);
		}

		// Query running containers to record instances
		try {
			await this._recordContainerInstances(
				chapterId,
				chapter.worktreePath,
				composeFile,
				portMappings,
				env,
			);
		} catch (recordErr) {
			// Containers are running but DB has no record — tear them down to avoid port leak
			logger.error("Failed to record container instances, running compose down to clean up", {
				chapterId,
				error: String(recordErr),
			});
			await exec(["compose", "-f", composeFile, "down"], chapter.worktreePath, env);
			await portAllocator.release(chapterId);
			throw new ContainerError(`Containers started but recording failed, cleaned up: ${recordErr}`);
		}

		logger.info("Chapter containers started", { chapterId });
		eventBus.emit({ type: "container:started", chapterId });
	},

	/** Pause all containers for a chapter (used during dormant). */
	async pauseChapterContainers(chapterId: string): Promise<void> {
		const chapter = await db.query.chapters.findFirst({ where: eq(chapters.id, chapterId) });
		if (!chapter) throw new NotFoundError("Chapter", chapterId);

		const config = chapter.containerConfig as ContainerConfig | null;
		const worktreePath = chapter.worktreePath;
		if (!worktreePath) return;

		const composeFile = resolveComposeFile(worktreePath, config);
		if (!composeFile) return;

		const result = await exec(["compose", "-f", composeFile, "pause"], worktreePath);
		if (result.exitCode !== 0) {
			logger.warn("Failed to pause containers", { chapterId, stderr: result.stderr });
			return;
		}

		const now = new Date().toISOString();
		await db
			.update(containerInstances)
			.set({ status: "paused", updatedAt: now })
			.where(eq(containerInstances.chapterId, chapterId));

		logger.info("Chapter containers paused", { chapterId });
	},

	/** Unpause all containers for a chapter (used during wake). */
	async unpauseChapterContainers(chapterId: string): Promise<void> {
		const chapter = await db.query.chapters.findFirst({ where: eq(chapters.id, chapterId) });
		if (!chapter) throw new NotFoundError("Chapter", chapterId);
		if (!chapter.worktreePath) throw new ValidationError("Chapter has no worktree");

		const config = chapter.containerConfig as ContainerConfig | null;
		const composeFile = resolveComposeFile(chapter.worktreePath, config);
		if (!composeFile) return;

		const result = await exec(["compose", "-f", composeFile, "unpause"], chapter.worktreePath);
		if (result.exitCode !== 0) {
			// Containers may have been removed — clean up stale records and do a fresh start
			logger.warn("Unpause failed, attempting fresh start", { chapterId });
			await this.removeChapterContainers(chapterId);
			await this.startChapterContainers(chapterId);
			return;
		}

		const now = new Date().toISOString();
		await db
			.update(containerInstances)
			.set({ status: "running", updatedAt: now })
			.where(eq(containerInstances.chapterId, chapterId));

		logger.info("Chapter containers unpaused", { chapterId });
	},

	/** Stop all containers for a chapter. */
	async stopChapterContainers(chapterId: string): Promise<void> {
		const chapter = await db.query.chapters.findFirst({ where: eq(chapters.id, chapterId) });
		if (!chapter) throw new NotFoundError("Chapter", chapterId);

		const config = chapter.containerConfig as ContainerConfig | null;
		const worktreePath = chapter.worktreePath;
		if (!worktreePath) return;

		const composeFile = resolveComposeFile(worktreePath, config);
		if (!composeFile) return;

		const result = await exec(["compose", "-f", composeFile, "stop"], worktreePath);
		if (result.exitCode !== 0) {
			logger.warn("Failed to stop containers", { chapterId, stderr: result.stderr });
		}

		const now = new Date().toISOString();
		await db
			.update(containerInstances)
			.set({ status: "stopped", updatedAt: now })
			.where(eq(containerInstances.chapterId, chapterId));

		eventBus.emit({ type: "container:stopped", chapterId });
		logger.info("Chapter containers stopped", { chapterId });
	},

	/**
	 * Remove all containers for a chapter (used during cleanup).
	 * Optionally deletes volumes.
	 */
	async removeChapterContainers(
		chapterId: string,
		opts: { deleteVolumes?: boolean } = {},
	): Promise<void> {
		const chapter = await db.query.chapters.findFirst({ where: eq(chapters.id, chapterId) });
		if (!chapter) throw new NotFoundError("Chapter", chapterId);

		const config = chapter.containerConfig as ContainerConfig | null;
		const worktreePath = chapter.worktreePath;

		// Try to run compose down if worktree exists
		if (worktreePath) {
			const composeFile = resolveComposeFile(worktreePath, config);
			if (composeFile) {
				const args = ["compose", "-f", composeFile, "down"];
				if (opts.deleteVolumes) args.push("-v");

				const result = await exec(args, worktreePath);
				if (result.exitCode !== 0) {
					logger.warn("Failed to remove containers via compose", {
						chapterId,
						stderr: result.stderr,
					});
				}
			}
		}

		// Clean up DB records regardless
		await db.delete(containerInstances).where(eq(containerInstances.chapterId, chapterId));
		await portAllocator.release(chapterId);

		eventBus.emit({ type: "container:stopped", chapterId });
		logger.info("Chapter containers removed", { chapterId, deleteVolumes: opts.deleteVolumes });
	},

	/** Get container logs for a chapter. */
	async getContainerLogs(
		chapterId: string,
		opts: { tail?: number; service?: string } = {},
	): Promise<string> {
		const chapter = await db.query.chapters.findFirst({ where: eq(chapters.id, chapterId) });
		if (!chapter) throw new NotFoundError("Chapter", chapterId);
		if (!chapter.worktreePath) throw new ValidationError("Chapter has no worktree");

		const config = chapter.containerConfig as ContainerConfig | null;
		const composeFile = resolveComposeFile(chapter.worktreePath, config);
		if (!composeFile) return "";

		const args = ["compose", "-f", composeFile, "logs"];
		if (opts.tail) args.push("--tail", String(opts.tail));
		if (opts.service) args.push(opts.service);

		const result = await exec(args, chapter.worktreePath);
		return result.stdout || result.stderr;
	},

	/** List container instances for a chapter from DB. */
	async listByChapter(chapterId: string) {
		return db.query.containerInstances.findMany({
			where: eq(containerInstances.chapterId, chapterId),
		});
	},

	/**
	 * @internal Record container instances by querying compose ps.
	 */
	async _recordContainerInstances(
		chapterId: string,
		worktreePath: string,
		composeFile: string,
		portMappings: PortMapping[],
		env: Record<string, string>,
	): Promise<void> {
		const result = await exec(
			["compose", "-f", composeFile, "ps", "--format", "json"],
			worktreePath,
			env,
		);

		const now = new Date().toISOString();

		if (result.exitCode === 0 && result.stdout) {
			// compose ps --format json may output one JSON object per line or an array
			const lines = result.stdout.split("\n").filter(Boolean);
			for (const line of lines) {
				try {
					const parsed = JSON.parse(line);
					const containers = Array.isArray(parsed) ? parsed : [parsed];
					for (const container of containers) {
						const serviceName = container.Service || container.Name || "unknown";
						const portMapping = portMappings.find((p) => p.serviceName === serviceName);

						await db.insert(containerInstances).values({
							id: generateId(),
							chapterId,
							containerId: container.ID || container.Id || null,
							serviceName,
							status: "running",
							hostPort: portMapping?.hostPort ?? null,
							containerPort: portMapping?.containerPort ?? null,
							createdAt: now,
							updatedAt: now,
						});
					}
				} catch {
					logger.warn("Failed to parse compose ps output line", { line });
				}
			}
		} else {
			// Fallback: create instances from port mappings if ps failed
			for (const { hostPort, containerPort, serviceName } of portMappings) {
				await db.insert(containerInstances).values({
					id: generateId(),
					chapterId,
					serviceName,
					status: "running",
					hostPort,
					containerPort,
					createdAt: now,
					updatedAt: now,
				});
			}
		}
	},
};
