import { generateId } from "@server/lib/id";
import {
	type JsonRpcNotification,
	type JsonValue,
	PROVIDER_PROTOCOL_VERSION,
	PROVIDER_REQUEST_MAX_BYTES,
	PROVIDER_SEARCH_METHOD,
	type ProviderStreamEvent,
	providerEventSchema,
} from "@server/lib/plugins/protocol";
import type { PluginRuntime } from "./plugin-runtime";

const textEncoder = new TextEncoder();

const DEFAULT_STREAM_WINDOW: ProviderStreamWindow = {
	maxUnackedEvents: 64,
	maxUnackedBytes: 256 * 1024,
	terminalReserveEvents: 2,
	terminalReserveBytes: 64 * 1024,
};

const DEFAULT_LIMITS: ProviderRpcLimits = {
	maxInFlightOperations: 8,
	maxQueueEvents: 66,
	maxQueueBytes: 320 * 1024,
	maxTotalQueueBytes: 2 * 1024 * 1024,
	maxFrameBytes: 256 * 1024,
	maxUnaryResponseBytes: 1024 * 1024,
	maxRequestBytes: PROVIDER_REQUEST_MAX_BYTES,
	maxOperationOutputBytes: 24 * 1024 * 1024,
	maxTextBytes: 8 * 1024 * 1024,
	maxReasoningBytes: 8 * 1024 * 1024,
	maxToolArgumentBytes: 2 * 1024 * 1024,
	maxAllToolArgumentBytes: 8 * 1024 * 1024,
	maxDeltaBytes: 64 * 1024,
	maxEventsPerOperation: 100_000,
	acceptedTimeoutMs: 5_000,
	unaryTimeoutMs: 30_000,
	streamIdleTimeoutMs: 5 * 60_000,
	operationTimeoutMs: 30 * 60_000,
	cancelGraceMs: 5_000,
	maxLateEvents: 3,
};

export interface ProviderRpcRequestOptions {
	signal?: AbortSignal;
	timeoutMs?: number;
	/** Correlation ID generated by the provider operation registry. */
	requestId?: string;
}

/**
 * Narrow transport boundary used by the provider client. PluginRuntime satisfies
 * request/notify; notification and crash subscriptions are injected so tests and
 * future runtime wiring do not need to reimplement Content-Length framing.
 */
export interface ProviderRpcTransport {
	request<T = unknown>(
		method: string,
		params?: unknown,
		options?: ProviderRpcRequestOptions,
	): Promise<T>;
	notify(method: string, params?: unknown): Promise<void>;
	onNotification?(
		handler: (notification: JsonRpcNotification, bodyBytes?: number) => void,
	): () => void;
	onClose?(handler: (error?: Error) => void): () => void;
	kill?(reason: string): void | Promise<void>;
}

export interface PluginRuntimeProviderTransportOptions {
	subscribeNotifications?: (
		handler: (notification: JsonRpcNotification, bodyBytes?: number) => void,
	) => () => void;
	subscribeClose?: (handler: (error?: Error) => void) => () => void;
	kill?: (reason: string) => void | Promise<void>;
}

/** Adapts PluginRuntime without replacing its request registry or stdio framing. */
export class PluginRuntimeProviderTransport implements ProviderRpcTransport {
	constructor(
		private readonly runtime: Pick<PluginRuntime, "request" | "notify" | "quarantine">,
		private readonly options: PluginRuntimeProviderTransportOptions = {},
	) {}

	request<T = unknown>(
		method: string,
		params?: unknown,
		options: ProviderRpcRequestOptions = {},
	): Promise<T> {
		return this.runtime.request<T>(method, params, {
			signal: options.signal,
			timeoutMs: options.timeoutMs,
		});
	}

	notify(method: string, params?: unknown): Promise<void> {
		return this.runtime.notify(method, params);
	}

	onNotification(
		handler: (notification: JsonRpcNotification, bodyBytes?: number) => void,
	): () => void {
		return this.options.subscribeNotifications?.(handler) ?? (() => undefined);
	}

	onClose(handler: (error?: Error) => void): () => void {
		return this.options.subscribeClose?.(handler) ?? (() => undefined);
	}

	kill(reason: string): void | Promise<void> {
		if (this.options.kill) return this.options.kill(reason);
		this.runtime.quarantine(reason);
	}
}

export interface ProviderStreamWindow {
	maxUnackedEvents: number;
	maxUnackedBytes: number;
	terminalReserveEvents: number;
	terminalReserveBytes: number;
}

export interface ProviderRpcLimits {
	maxInFlightOperations: number;
	maxQueueEvents: number;
	maxQueueBytes: number;
	maxTotalQueueBytes: number;
	maxFrameBytes: number;
	maxUnaryResponseBytes: number;
	maxRequestBytes: number;
	maxOperationOutputBytes: number;
	maxTextBytes: number;
	maxReasoningBytes: number;
	maxToolArgumentBytes: number;
	maxAllToolArgumentBytes: number;
	maxDeltaBytes: number;
	maxEventsPerOperation: number;
	acceptedTimeoutMs: number;
	unaryTimeoutMs: number;
	streamIdleTimeoutMs: number;
	operationTimeoutMs: number;
	cancelGraceMs: number;
	maxLateEvents: number;
}

export interface ProviderDescriptor {
	pluginId: string;
	providerTypeId: string;
	localId: string;
	displayName: string;
	description?: string;
	configSchema: Record<string, JsonValue>;
	defaultModelId?: string;
	capabilities: {
		validateConfig: true;
		listModels: true;
		chat: true;
		generate: boolean;
		reasoningContinuation?: boolean;
		inputImages?: boolean;
		mayLeakXmlToolCalls?: boolean;
	};
	limits: {
		maxConcurrentChat: number;
		maxConcurrentGenerate: number;
		maxConfigBytes: number;
		maxModelPageSize: number;
	};
}

export interface ProviderDescribeResult {
	selectedProtocolVersion: string;
	plugin: {
		id: string;
		name: string;
		version: string;
	};
	providers: ProviderDescriptor[];
}

export interface ProviderModelDescriptor {
	id: string;
	displayName: string;
	description?: string;
	aliases?: string[];
	contextWindow?: number;
	maxOutputTokens?: number;
	deprecated?: boolean;
	deprecationMessage?: string;
	capabilities: {
		chat: boolean;
		generate: boolean;
		streaming: boolean;
		tools: boolean;
		parallelToolCalls?: boolean;
		inputImages?: boolean;
		reasoning?: boolean;
		reasoningEfforts?: Array<"none" | "low" | "medium" | "high" | "xhigh" | "max">;
		sessionMode: "stateless" | "stateful";
	};
	metadata?: Record<string, JsonValue>;
}

export interface ModelCatalog {
	models: ProviderModelDescriptor[];
	nextCursor?: string;
	catalogVersion?: string;
	cacheTtlMs?: number;
	stale?: boolean;
}

export interface ValidateConfigIssue {
	severity: "error" | "warning" | "info";
	code: string;
	path?: string;
	message: string;
	retryable?: boolean;
}

export interface ValidateConfigResult {
	valid: boolean;
	issues: ValidateConfigIssue[];
	capabilities?: Record<string, JsonValue>;
}

/**
 * Host-provided hints delivered with every provider method call.
 *
 * See `providerHostHintsSchema` in `protocol.ts` for the full design rationale:
 * - `outbound.proxyUrl`: proxy URL from the host's global settings (secret-grade, never logged)
 * - `concurrency.maxConcurrentUpstream`: cooperative upstream concurrency cap
 *
 * Both are optional hints. A well-behaved plugin should:
 * - Use `outbound.proxyUrl` as its HTTP(S) proxy when making upstream API calls
 * - Respect `concurrency.maxConcurrentUpstream` as a ceiling on its own connection pool
 *
 * The host omits the entire `hostHints` field when there is nothing to communicate.
 */
export interface ProviderHostHints {
	outbound?: { proxyUrl?: string };
	concurrency?: { maxConcurrentUpstream?: number };
}

export interface ProviderBaseParams {
	providerTypeId: string;
	providerInstanceId: string;
	providerPrefix: string;
	config: Record<string, JsonValue>;
	modelId: string;
	/**
	 * Host-provided network and concurrency hints.
	 *
	 * Absent = host has no opinion. See `ProviderHostHints` for field semantics.
	 * SECURITY: `outbound.proxyUrl` may contain credentials — never log or expose it.
	 */
	hostHints?: ProviderHostHints;
}

export interface ValidateConfigParams {
	providerTypeId: string;
	providerInstanceId: string;
	config: Record<string, JsonValue>;
	mode: "syntax" | "connectivity";
	modelId?: string;
	/** Host-provided network hints (proxy). */
	hostHints?: ProviderHostHints;
}

export interface ListModelsParams {
	providerTypeId: string;
	providerInstanceId: string;
	config: Record<string, JsonValue>;
	cursor?: string;
	limit?: number;
	refresh?: boolean;
	query?: string;
	/** Host-provided network hints (proxy). */
	hostHints?: ProviderHostHints;
}

/**
 * Params for `provider.search`.
 *
 * `providerTypeId` is the *bound provider* contribution: a search source has no config of its
 * own and both the descriptor lookup and the config byte limit are the bound provider's (see
 * `searchProviderContributionSchema`). `contributionId` names the search source itself.
 */
export interface ProviderSearchParams {
	providerTypeId: string;
	providerInstanceId: string;
	config: Record<string, JsonValue>;
	contributionId: string;
	query: string;
	purpose?: string;
	allowedDomains?: string[];
	blockedDomains?: string[];
	recencyDays?: number;
	maxResults?: number;
	locale?: string;
	/** Manifest-declared ceiling; the caller clamps it against the transport's own timeout. */
	timeoutMs?: number;
	/**
	 * Manifest-declared response ceiling, clamped against the transport's own unary limit the
	 * same way `timeoutMs` is. Declaring a smaller budget than the host allows is meaningful —
	 * it is a promise the plugin is held to — so it is enforced rather than merely recorded.
	 */
	maxOutputBytes?: number;
	/** Host-provided network and concurrency hints. */
	hostHints?: ProviderHostHints;
}

export interface ProviderSearchResultItem {
	title?: string;
	url?: string;
	snippet?: string;
	publishedAt?: string;
	source?: string;
}

export interface ProviderSearchResult {
	text?: string;
	results?: ProviderSearchResultItem[];
}

export interface ProviderContentBlock {
	type: string;
	[key: string]: JsonValue;
}

export interface ProviderMessage {
	role: "system" | "user" | "assistant" | "tool";
	content: ProviderContentBlock[];
	messageId?: string;
}

export interface ProviderToolDefinition {
	name: string;
	description: string;
	inputSchema: Record<string, JsonValue>;
}

export interface ProviderChatParams extends ProviderBaseParams {
	conversation: {
		conversationId: string;
		stickySessionKey?: string;
		resetUpstreamSession?: boolean;
	};
	request: {
		history: ProviderMessage[];
		current: {
			text: string;
			images?: Array<{ mediaType: string; dataBase64: string }>;
			toolResults: ProviderContentBlock[];
		};
		tools: ProviderToolDefinition[];
		options?: {
			reasoningEffort?: "none" | "low" | "medium" | "high" | "xhigh" | "max";
			serviceTier?: string;
			metadata?: Record<string, JsonValue>;
			locale?: string;
		};
	};
}

export interface ProviderGenerateParams extends ProviderBaseParams {
	request:
		| {
				mode: "prompt";
				text: string;
				systemInstruction?: string;
		  }
		| {
				mode: "history";
				systemInstruction: string;
				content: string;
				locale?: string;
		  };
	options?: {
		reasoningEffort?: "none" | "low" | "medium" | "high" | "xhigh" | "max";
	};
}

export type ProviderOperationKind = "chat" | "generate";
export type ProviderOperationState =
	| "accepting"
	| "streaming"
	| "cancelling"
	| "terminal_received"
	| "failed"
	| "closed";
export type ProviderCancelReason =
	| "user_abort"
	| "timeout"
	| "output_limit"
	| "shutdown"
	| "superseded";

export interface ProviderCancelResult {
	operationId: string;
	state: "cancelling" | "already_done" | "unknown_operation";
}

export interface ProviderOperation extends AsyncIterable<ProviderStreamEvent> {
	readonly operationId: string;
	readonly requestId: string;
	readonly kind: ProviderOperationKind;
	readonly state: ProviderOperationState;
	readonly accepted: boolean;
	readonly exposedToolCall: boolean;
	readonly replaySafe: boolean;
	events(): AsyncGenerator<ProviderStreamEvent>;
	cancel(reason?: ProviderCancelReason, message?: string): Promise<ProviderCancelResult>;
}

export type ProviderRpcErrorCode =
	| "NOT_DESCRIBED"
	| "INCOMPATIBLE_PROTOCOL"
	| "INVALID_RESPONSE"
	| "PROTOCOL_ERROR"
	| "PLUGIN_BUSY"
	| "FRAME_LIMIT"
	| "QUEUE_LIMIT"
	| "CREDIT_EXCEEDED"
	| "OUTPUT_LIMIT"
	| "ACCEPT_TIMEOUT"
	| "STREAM_IDLE_TIMEOUT"
	| "OPERATION_TIMEOUT"
	| "CANCEL_TIMEOUT"
	| "CANCELLED"
	| "UNKNOWN_RESULT"
	| "TRANSPORT_ERROR";

export class ProviderRpcError extends Error {
	readonly code: ProviderRpcErrorCode;
	readonly operationId?: string;
	readonly requestId?: string;
	readonly retryable: boolean;
	readonly unknownResult: boolean;
	readonly exposedToolCall: boolean;
	readonly replaySafe: boolean;

	constructor(
		code: ProviderRpcErrorCode,
		message: string,
		options: {
			operationId?: string;
			requestId?: string;
			retryable?: boolean;
			unknownResult?: boolean;
			exposedToolCall?: boolean;
			replaySafe?: boolean;
			cause?: unknown;
		} = {},
	) {
		super(message, { cause: options.cause });
		this.name = "ProviderRpcError";
		this.code = code;
		this.operationId = options.operationId;
		this.requestId = options.requestId;
		this.retryable = options.retryable ?? false;
		this.unknownResult = options.unknownResult ?? false;
		this.exposedToolCall = options.exposedToolCall ?? false;
		this.replaySafe = options.replaySafe ?? false;
	}
}

export interface PluginProviderRpcClientOptions {
	transport: ProviderRpcTransport;
	protocolVersions?: string[];
	expectedPluginId?: string;
	host?: {
		name?: string;
		version?: string;
		platform?: string;
		arch?: string;
	};
	streamWindow?: Partial<ProviderStreamWindow>;
	limits?: Partial<ProviderRpcLimits>;
	idFactory?: (prefix: "op" | "rpc") => string;
	onProtocolViolation?: (error: ProviderRpcError) => void;
}

export interface ProviderRpcDiagnostics {
	selectedProtocolVersion?: string;
	activeOperations: number;
	queuedBytes: number;
	lateEvents: number;
	protocolErrors: number;
	transportKilled: boolean;
	operations: Array<{
		operationId: string;
		requestId: string;
		kind: ProviderOperationKind;
		state: ProviderOperationState;
		nextSeq: number;
		queuedEvents: number;
		queuedBytes: number;
		exposedToolCall: boolean;
	}>;
}

interface AcceptedResult {
	accepted: true;
	operationId: string;
}

interface QueuedEvent {
	event: ProviderStreamEvent;
	seq: number;
	bodyBytes: number;
	creditKind: "normal" | "terminal";
}

const MAX_PRE_ACCEPTED_EVENTS = 32;
const MAX_PRE_ACCEPTED_BYTES = 256 * 1024;

interface EventWaiter {
	resolve: (result: IteratorResult<ProviderStreamEvent>) => void;
	reject: (error: Error) => void;
}

interface ToolCallState {
	mode: "streaming" | "complete";
	ended: boolean;
	bytes: number;
}

interface OperationRecord {
	operationId: string;
	requestId: string;
	providerTypeId: string;
	kind: ProviderOperationKind;
	state: ProviderOperationState;
	accepted: boolean;
	nextSeq: number;
	preAcceptedEvents: QueuedEvent[];
	preAcceptedBytes: number;
	queue: QueuedEvent[];
	queuedBytes: number;
	waiter?: EventWaiter;
	iteratorClaimed: boolean;
	iteratorCompleted: boolean;
	usedNormalEvents: number;
	usedNormalBytes: number;
	usedTerminalEvents: number;
	usedTerminalBytes: number;
	eventCount: number;
	operationOutputBytes: number;
	textBytes: number;
	reasoningBytes: number;
	allToolArgumentBytes: number;
	toolCalls: Map<string, ToolCallState>;
	allowedToolNames: Set<string>;
	exposedToolCall: boolean;
	hasVisibleOutput: boolean;
	sawError: boolean;
	terminalError?: Error;
	postDoneError?: Error;
	cancelPromise?: Promise<ProviderCancelResult>;
	cancelTimer?: ReturnType<typeof setTimeout>;
	idleTimer?: ReturnType<typeof setTimeout>;
	totalTimer?: ReturnType<typeof setTimeout>;
	removeAbort?: () => void;
	publicOperation?: ProviderOperationImpl;
}

class ProviderOperationImpl implements ProviderOperation {
	constructor(
		private readonly client: PluginProviderRpcClient,
		private readonly record: OperationRecord,
	) {}

	get operationId(): string {
		return this.record.operationId;
	}

	get requestId(): string {
		return this.record.requestId;
	}

	get kind(): ProviderOperationKind {
		return this.record.kind;
	}

	get state(): ProviderOperationState {
		return this.record.state;
	}

	get accepted(): boolean {
		return this.record.accepted;
	}

	get exposedToolCall(): boolean {
		return this.record.exposedToolCall;
	}

	get replaySafe(): boolean {
		return !this.record.exposedToolCall && !this.record.hasVisibleOutput;
	}

	events(): AsyncGenerator<ProviderStreamEvent> {
		return this.client.iterateOperation(this.record);
	}

	[Symbol.asyncIterator](): AsyncIterator<ProviderStreamEvent> {
		return this.events();
	}

	cancel(
		reason: ProviderCancelReason = "user_abort",
		message?: string,
	): Promise<ProviderCancelResult> {
		return this.client.cancel(this.record.operationId, reason, message);
	}
}

export class PluginProviderRpcClient {
	private readonly transport: ProviderRpcTransport;
	private readonly protocolVersions: string[];
	private readonly expectedPluginId?: string;
	private readonly host: Required<NonNullable<PluginProviderRpcClientOptions["host"]>>;
	private readonly streamWindow: ProviderStreamWindow;
	private readonly limits: ProviderRpcLimits;
	private readonly idFactory: (prefix: "op" | "rpc") => string;
	private readonly onProtocolViolation?: (error: ProviderRpcError) => void;
	private readonly operations = new Map<string, OperationRecord>();
	private readonly requests = new Map<string, OperationRecord>();
	private readonly closedOperationIds = new Set<string>();
	private readonly descriptors = new Map<string, ProviderDescriptor>();
	private unsubscribeNotification?: () => void;
	private unsubscribeClose?: () => void;
	private describeResult?: ProviderDescribeResult;
	private selectedProtocolVersion?: string;
	private queuedBytes = 0;
	private lateEvents = 0;
	private protocolErrors = 0;
	private transportKilled = false;
	private disposed = false;

	constructor(options: PluginProviderRpcClientOptions | ProviderRpcTransport) {
		const normalized = isTransport(options) ? { transport: options } : options;
		this.transport = normalized.transport;
		this.protocolVersions = normalizeProtocolVersions(
			normalized.protocolVersions ?? [PROVIDER_PROTOCOL_VERSION],
		);
		this.expectedPluginId = normalized.expectedPluginId;
		this.host = {
			name: normalized.host?.name ?? "narrafork",
			version: normalized.host?.version ?? "unknown",
			platform: normalized.host?.platform ?? process.platform,
			arch: normalized.host?.arch ?? process.arch,
		};
		this.streamWindow = normalizeWindow(normalized.streamWindow);
		this.limits = normalizeLimits(normalized.limits, this.streamWindow);
		this.idFactory = normalized.idFactory ?? ((prefix) => `${prefix}_${generateId(12)}`);
		this.onProtocolViolation = normalized.onProtocolViolation;
		this.unsubscribeNotification = this.transport.onNotification?.((message, bodyBytes) => {
			// The plugin normally sends the accepted response before its first provider.event, but
			// stdout scheduling can expose the frames to the host in separate tasks. Defer handling
			// once so same-chunk responses settle first; handleNotification also keeps a bounded
			// pre-accepted buffer for the remaining transport-level reordering window.
			queueMicrotask(() => this.handleNotification(message, bodyBytes));
		});
		this.unsubscribeClose = this.transport.onClose?.((error) => {
			this.handleTransportClose(error);
		});
	}

	get descriptor(): ProviderDescribeResult | undefined {
		return this.describeResult;
	}

	get protocolVersion(): string | undefined {
		return this.selectedProtocolVersion;
	}

	async describe(
		overrides: {
			protocolVersions?: string[];
			host?: Partial<PluginProviderRpcClientOptions["host"]>;
		} = {},
	): Promise<ProviderDescribeResult> {
		this.assertUsable();
		const protocolVersions = normalizeProtocolVersions(
			overrides.protocolVersions ?? this.protocolVersions,
		);
		const result = await this.transport.request<unknown>(
			"provider.describe",
			{
				protocolVersions,
				host: { ...this.host, ...(overrides.host ?? {}) },
				limits: {
					maxInboundFrameBytes: this.limits.maxUnaryResponseBytes,
					maxOperationOutputBytes: this.limits.maxOperationOutputBytes,
				},
			},
			{ timeoutMs: this.limits.unaryTimeoutMs, requestId: this.nextRequestId() },
		);
		this.assertUnarySize(result, "provider.describe");
		const normalized = normalizeDescribeResult(result, protocolVersions, this.expectedPluginId);
		this.describeResult = normalized;
		this.selectedProtocolVersion = normalized.selectedProtocolVersion;
		this.descriptors.clear();
		for (const descriptor of normalized.providers) {
			this.descriptors.set(descriptor.providerTypeId, descriptor);
		}
		return cloneJson(normalized);
	}

	async validateConfig(
		params: ValidateConfigParams,
		signal?: AbortSignal,
	): Promise<ValidateConfigResult> {
		const protocolVersion = this.requireProtocolVersion();
		this.requireDescriptor(params.providerTypeId);
		this.assertConfigLimit(params.providerTypeId, params.config);
		const request = { protocolVersion, ...params };
		this.assertRequestSize(request, "provider.validateConfig");
		const result = await this.transport.request<unknown>("provider.validateConfig", request, {
			signal,
			timeoutMs: params.mode === "connectivity" ? this.limits.unaryTimeoutMs : 5_000,
			requestId: this.nextRequestId(),
		});
		this.assertUnarySize(result, "provider.validateConfig");
		return normalizeValidateConfigResult(result);
	}

	async listModels(params: ListModelsParams, signal?: AbortSignal): Promise<ModelCatalog> {
		const protocolVersion = this.requireProtocolVersion();
		this.requireDescriptor(params.providerTypeId);
		this.assertConfigLimit(params.providerTypeId, params.config);
		const descriptor = this.descriptors.get(params.providerTypeId);
		const maximum = Math.min(200, descriptor?.limits.maxModelPageSize ?? 200);
		const limit = params.limit ?? Math.min(100, maximum);
		if (!Number.isSafeInteger(limit) || limit < 1 || limit > maximum) {
			throw new ProviderRpcError(
				"INVALID_RESPONSE",
				`provider.listModels limit must be between 1 and ${maximum}`,
			);
		}
		const request = { protocolVersion, ...params, limit };
		this.assertRequestSize(request, "provider.listModels");
		const result = await this.transport.request<unknown>("provider.listModels", request, {
			signal,
			timeoutMs: this.limits.unaryTimeoutMs,
			requestId: this.nextRequestId(),
		});
		this.assertUnarySize(result, "provider.listModels");
		return normalizeModelCatalog(result, maximum);
	}

	/**
	 * Run one web search through a `contributes.searchProviders` source.
	 *
	 * Unary, unlike `chat`/`generate`: no operation id, no accepted/event/done triple. The
	 * host's search router awaits one result per channel and falls through on failure, so
	 * there is nothing for a stream to feed. Checks mirror `listModels` exactly so byte caps
	 * and timeouts behave the same way.
	 */
	async search(params: ProviderSearchParams, signal?: AbortSignal): Promise<ProviderSearchResult> {
		const protocolVersion = this.requireProtocolVersion();
		this.requireDescriptor(params.providerTypeId);
		this.assertConfigLimit(params.providerTypeId, params.config);
		const {
			providerTypeId: _type,
			providerInstanceId: _instance,
			timeoutMs,
			maxOutputBytes,
			...rest
		} = params;
		const request = { protocolVersion, ...rest };
		this.assertRequestSize(request, PROVIDER_SEARCH_METHOD);
		// A manifest may ask for less time than the transport allows, never more: the ceiling
		// exists so one plugin cannot hold a search channel open past the host's own budget.
		const effectiveTimeout = Math.min(
			timeoutMs ?? this.limits.unaryTimeoutMs,
			this.limits.unaryTimeoutMs,
		);
		const result = await this.transport.request<unknown>(PROVIDER_SEARCH_METHOD, request, {
			signal,
			timeoutMs: effectiveTimeout,
			requestId: this.nextRequestId(),
		});
		// Same clamp shape as the timeout: the host cap always wins, and a manifest that
		// declared a tighter budget is held to it instead of silently getting the full 1 MB.
		this.assertUnarySize(result, PROVIDER_SEARCH_METHOD, maxOutputBytes);
		return normalizeSearchResult(result);
	}

	chat(
		params: ProviderChatParams,
		options: { signal?: AbortSignal } = {},
	): Promise<ProviderOperation> {
		return this.startOperation("chat", params, options.signal);
	}

	generate(
		params: ProviderGenerateParams,
		options: { signal?: AbortSignal } = {},
	): Promise<ProviderOperation> {
		return this.startOperation("generate", params, options.signal);
	}

	async cancel(
		operation: string | ProviderOperation,
		reason: ProviderCancelReason = "user_abort",
		message?: string,
	): Promise<ProviderCancelResult> {
		const operationId = typeof operation === "string" ? operation : operation.operationId;
		const record = this.operations.get(operationId);
		if (!record) {
			if (this.closedOperationIds.has(operationId)) {
				return { operationId, state: "already_done" };
			}
			const protocolVersion = this.requireProtocolVersion();
			return normalizeCancelResult(
				await this.transport.request<unknown>(
					"provider.cancel",
					{ protocolVersion, operationId, reason, ...(message ? { message } : {}) },
					{ timeoutMs: this.limits.acceptedTimeoutMs, requestId: this.nextRequestId() },
				),
				operationId,
			);
		}
		return this.beginCancel(record, reason, message, cancelErrorFor(reason, record));
	}

	/** Routes a provider.event notification received from PluginRuntime. */
	handleNotification(notification: JsonRpcNotification, bodyBytes?: number): boolean {
		if (this.disposed || notification.method !== "provider.event") return false;
		const bytes = bodyBytes ?? byteLength(notification);
		if (!safePositiveInteger(bytes) || bytes > this.limits.maxFrameBytes) {
			this.protocolViolation(undefined, "FRAME_LIMIT", "provider.event frame exceeded the limit");
			return true;
		}
		const parsed = providerEventSchema.safeParse(notification);
		if (!parsed.success) {
			this.protocolViolation(undefined, "PROTOCOL_ERROR", "Malformed provider.event notification");
			return true;
		}
		const { operationId, seq, event, protocolVersion } = parsed.data.params;
		if (protocolVersion !== this.selectedProtocolVersion) {
			this.protocolViolation(
				this.operations.get(operationId),
				"PROTOCOL_ERROR",
				"provider.event protocol version mismatch",
			);
			return true;
		}
		const record = this.operations.get(operationId);
		if (!record) {
			this.recordLateEvent(operationId);
			return true;
		}
		if (record.state === "accepting" && !record.accepted) {
			this.bufferPreAcceptedEvent(record, event, seq, bytes);
			return true;
		}
		if (!record.accepted) {
			this.recordLateEvent(operationId);
			return true;
		}
		this.receiveAcceptedEvent(record, event, seq, bytes);
		return true;
	}

	/** Fails all accepted operations with an unknown-result transport error. */
	handleTransportClose(error?: Error): void {
		if (this.disposed) return;
		for (const record of [...this.operations.values()]) {
			const replaySafe = !record.exposedToolCall && !record.hasVisibleOutput;
			this.failOperation(
				record,
				new ProviderRpcError(
					record.accepted ? "UNKNOWN_RESULT" : "TRANSPORT_ERROR",
					record.accepted
						? "Provider process exited before the operation result was known"
						: "Provider transport closed before the operation was accepted",
					{
						operationId: record.operationId,
						requestId: record.requestId,
						retryable: replaySafe,
						unknownResult: record.accepted,
						exposedToolCall: record.exposedToolCall,
						replaySafe,
						cause: error,
					},
				),
			);
		}
	}

	getOperation(id: string): ProviderOperation | undefined {
		return (this.operations.get(id) ?? this.requests.get(id))?.publicOperation;
	}

	getDiagnostics(): ProviderRpcDiagnostics {
		return {
			selectedProtocolVersion: this.selectedProtocolVersion,
			activeOperations: this.operations.size,
			queuedBytes: this.queuedBytes,
			lateEvents: this.lateEvents,
			protocolErrors: this.protocolErrors,
			transportKilled: this.transportKilled,
			operations: [...this.operations.values()].map((record) => ({
				operationId: record.operationId,
				requestId: record.requestId,
				kind: record.kind,
				state: record.state,
				nextSeq: record.nextSeq,
				queuedEvents: record.queue.length,
				queuedBytes: record.queuedBytes,
				exposedToolCall: record.exposedToolCall,
			})),
		};
	}

	async dispose(): Promise<void> {
		if (this.disposed) return;
		this.disposed = true;
		this.unsubscribeNotification?.();
		this.unsubscribeClose?.();
		for (const record of [...this.operations.values()]) {
			if (record.state !== "failed" && record.state !== "terminal_received") {
				const error = new ProviderRpcError("CANCELLED", "Provider RPC client disposed", {
					operationId: record.operationId,
					requestId: record.requestId,
				});
				void this.beginCancel(record, "shutdown", undefined, error);
				this.failOperation(record, error);
			}
			// Cancellation is best-effort once subscriptions are detached. No old client's
			// grace/idle timer may quarantine a runtime reused by a replacement client.
			this.finishOperation(record);
		}
	}

	async *iterateOperation(record: OperationRecord): AsyncGenerator<ProviderStreamEvent> {
		if (record.iteratorClaimed) {
			throw new ProviderRpcError(
				"PROTOCOL_ERROR",
				"A provider operation can only be consumed once",
				{
					operationId: record.operationId,
					requestId: record.requestId,
				},
			);
		}
		record.iteratorClaimed = true;
		let completed = false;
		try {
			while (true) {
				const result = await this.nextOperationEvent(record);
				if (result.done) {
					completed = true;
					return;
				}
				yield result.value;
			}
		} finally {
			record.iteratorCompleted = true;
			if (!completed && this.operations.has(record.operationId)) {
				void this.beginCancel(
					record,
					"superseded",
					"Provider event consumer closed before done",
					new ProviderRpcError("CANCELLED", "Provider event consumer closed", {
						operationId: record.operationId,
						requestId: record.requestId,
					}),
				);
			}
		}
	}

	private async startOperation(
		kind: ProviderOperationKind,
		params: ProviderChatParams | ProviderGenerateParams,
		signal?: AbortSignal,
	): Promise<ProviderOperation> {
		const protocolVersion = this.requireProtocolVersion();
		this.assertUsable();
		if (signal?.aborted) throw createAbortError(signal.reason);
		if (this.operations.size >= this.limits.maxInFlightOperations) {
			throw new ProviderRpcError("PLUGIN_BUSY", "Provider operation budget is exhausted", {
				retryable: true,
			});
		}
		this.assertConfigLimit(params.providerTypeId, params.config);
		const descriptor = this.descriptors.get(params.providerTypeId);
		if (kind === "generate" && descriptor && !descriptor.capabilities.generate) {
			throw new ProviderRpcError("INVALID_RESPONSE", "Provider does not support generate");
		}
		const activeForProvider = [...this.operations.values()].filter(
			(operation) => operation.providerTypeId === params.providerTypeId && operation.kind === kind,
		).length;
		const providerLimit =
			kind === "chat"
				? (descriptor?.limits.maxConcurrentChat ?? 1)
				: (descriptor?.limits.maxConcurrentGenerate ?? 1);
		if (activeForProvider >= providerLimit) {
			throw new ProviderRpcError(
				"PLUGIN_BUSY",
				`Provider ${kind} concurrency budget is exhausted`,
				{
					retryable: true,
				},
			);
		}
		const operationId = this.nextUniqueId("op", this.operations);
		const requestId = this.nextUniqueId("rpc", this.requests);
		const allowedToolNames =
			kind === "chat"
				? new Set((params as ProviderChatParams).request.tools.map((tool) => tool.name))
				: new Set<string>();
		const record: OperationRecord = {
			operationId,
			requestId,
			providerTypeId: params.providerTypeId,
			kind,
			state: "accepting",
			accepted: false,
			nextSeq: 1,
			preAcceptedEvents: [],
			preAcceptedBytes: 0,
			queue: [],
			queuedBytes: 0,
			iteratorClaimed: false,
			iteratorCompleted: false,
			usedNormalEvents: 0,
			usedNormalBytes: 0,
			usedTerminalEvents: 0,
			usedTerminalBytes: 0,
			eventCount: 0,
			operationOutputBytes: 0,
			textBytes: 0,
			reasoningBytes: 0,
			allToolArgumentBytes: 0,
			toolCalls: new Map(),
			allowedToolNames,
			exposedToolCall: false,
			hasVisibleOutput: false,
			sawError: false,
		};
		const publicOperation = new ProviderOperationImpl(this, record);
		record.publicOperation = publicOperation;
		this.operations.set(operationId, record);
		this.requests.set(requestId, record);
		record.totalTimer = setTimeout(() => {
			void this.beginCancel(
				record,
				"timeout",
				"Provider operation exceeded its total timeout",
				new ProviderRpcError("OPERATION_TIMEOUT", "Provider operation timed out", {
					operationId,
					requestId,
				}),
			);
		}, this.limits.operationTimeoutMs);
		if (signal) {
			const abort = () => {
				void this.beginCancel(record, "user_abort", undefined, createAbortError(signal.reason));
			};
			signal.addEventListener("abort", abort, { once: true });
			record.removeAbort = () => signal.removeEventListener("abort", abort);
		}

		const request = {
			protocolVersion,
			operationId,
			...params,
			streamWindow: this.streamWindow,
		};
		try {
			this.assertRequestSize(request, `provider.${kind}`);
			const result = await this.transport.request<unknown>(`provider.${kind}`, request, {
				signal,
				timeoutMs: this.limits.acceptedTimeoutMs,
				requestId,
			});
			const accepted = normalizeAcceptedResult(result, operationId);
			if (record.state !== "accepting") {
				throw record.terminalError ?? createAbortError(signal?.reason);
			}
			record.accepted = accepted.accepted;
			record.state = "streaming";
			this.armIdleTimer(record);
			this.flushPreAcceptedEvents(record);
			return publicOperation;
		} catch (error) {
			const normalized =
				error instanceof ProviderRpcError || error instanceof Error
					? error
					: new ProviderRpcError("TRANSPORT_ERROR", String(error));
			if (record.state === "accepting") this.failOperation(record, normalized);
			throw normalized;
		}
	}

	private bufferPreAcceptedEvent(
		record: OperationRecord,
		event: ProviderStreamEvent,
		seq: number,
		bodyBytes: number,
	): void {
		const expectedSeq = record.nextSeq + record.preAcceptedEvents.length;
		if (seq !== expectedSeq) {
			this.protocolViolation(
				record,
				"PROTOCOL_ERROR",
				`provider.event seq ${seq} did not match expected ${expectedSeq}`,
			);
			return;
		}
		if (
			record.preAcceptedEvents.length >= MAX_PRE_ACCEPTED_EVENTS ||
			record.preAcceptedBytes + bodyBytes > MAX_PRE_ACCEPTED_BYTES
		) {
			this.protocolViolation(
				record,
				"QUEUE_LIMIT",
				"Provider emitted too many events before accepted",
			);
			return;
		}
		record.preAcceptedEvents.push({
			event,
			seq,
			bodyBytes,
			creditKind: event.type === "error" || event.type === "done" ? "terminal" : "normal",
		});
		record.preAcceptedBytes += bodyBytes;
	}

	private flushPreAcceptedEvents(record: OperationRecord): void {
		const events = record.preAcceptedEvents;
		record.preAcceptedEvents = [];
		record.preAcceptedBytes = 0;
		for (const queued of events) {
			if (record.state === "failed" || record.state === "closed") return;
			this.receiveAcceptedEvent(record, queued.event, queued.seq, queued.bodyBytes);
		}
	}

	/** Buffered and live frames share sequence advancement and terminal-state checks. */
	private receiveAcceptedEvent(
		record: OperationRecord,
		event: ProviderStreamEvent,
		seq: number,
		bodyBytes: number,
	): void {
		if (
			record.state === "terminal_received" ||
			record.state === "failed" ||
			record.state === "closed"
		) {
			this.recordLateEvent(record.operationId);
			return;
		}
		if (seq !== record.nextSeq) {
			this.protocolViolation(
				record,
				"PROTOCOL_ERROR",
				`provider.event seq ${seq} did not match expected ${record.nextSeq}`,
			);
			return;
		}
		record.nextSeq += 1;
		this.receiveEvent(record, event, seq, bodyBytes);
	}

	private receiveEvent(
		record: OperationRecord,
		event: ProviderStreamEvent,
		seq: number,
		bodyBytes: number,
	): void {
		const terminal = event.type === "error" || event.type === "done";
		if (record.state === "cancelling" && !terminal) {
			this.recordLateEvent(record.operationId);
			return;
		}
		if (!this.consumeCredit(record, terminal ? "terminal" : "normal", bodyBytes)) return;
		if (!this.validateEventSemantics(record, event)) return;
		record.eventCount += 1;
		if (record.eventCount > this.limits.maxEventsPerOperation) {
			this.releaseCredit(record, terminal ? "terminal" : "normal", bodyBytes);
			this.outputLimit(record, "Provider operation exceeded its event limit");
			return;
		}
		if (!terminal) {
			record.operationOutputBytes += bodyBytes;
			if (record.operationOutputBytes > this.limits.maxOperationOutputBytes) {
				this.releaseCredit(record, "normal", bodyBytes);
				this.outputLimit(record, "Provider operation exceeded its output byte limit");
				return;
			}
		}
		if (event.type === "error") record.sawError = true;
		if (event.type === "done") {
			if (event.status === "failed" && !record.sawError) {
				this.releaseCredit(record, "terminal", bodyBytes);
				this.protocolViolation(
					record,
					"PROTOCOL_ERROR",
					"Failed done event was not preceded by error",
				);
				return;
			}
			if (event.status === "cancelled" && event.stopReason !== "cancelled") {
				this.releaseCredit(record, "terminal", bodyBytes);
				this.protocolViolation(
					record,
					"PROTOCOL_ERROR",
					"Cancelled done event must use the cancelled stop reason",
				);
				return;
			}
			record.state = "terminal_received";
			this.clearOperationTimers(record);
			if (event.status === "cancelled" && !record.postDoneError) {
				record.postDoneError = createAbortError();
			}
		}
		this.enqueueEvent(record, {
			event,
			seq,
			bodyBytes,
			creditKind: terminal ? "terminal" : "normal",
		});
	}

	private validateEventSemantics(record: OperationRecord, event: ProviderStreamEvent): boolean {
		if (record.kind === "generate" && event.type.startsWith("tool_call.")) {
			this.protocolViolation(record, "PROTOCOL_ERROR", "provider.generate emitted a tool call");
			return false;
		}
		if (event.type === "text.delta") {
			const bytes = utf8Bytes(event.text);
			if (bytes > this.limits.maxDeltaBytes) {
				this.protocolViolation(record, "FRAME_LIMIT", "text.delta exceeded the delta limit");
				return false;
			}
			record.textBytes += bytes;
			record.hasVisibleOutput = true;
			if (record.textBytes > this.limits.maxTextBytes) {
				this.outputLimit(record, "Provider text output exceeded the limit");
				return false;
			}
		}
		if (event.type === "reasoning.delta") {
			const bytes = utf8Bytes(event.text);
			if (bytes > this.limits.maxDeltaBytes) {
				this.protocolViolation(record, "FRAME_LIMIT", "reasoning.delta exceeded the delta limit");
				return false;
			}
			record.reasoningBytes += bytes;
			record.hasVisibleOutput = true;
			if (record.reasoningBytes > this.limits.maxReasoningBytes) {
				this.outputLimit(record, "Provider reasoning output exceeded the limit");
				return false;
			}
		}
		if (event.type === "reasoning.redacted") record.hasVisibleOutput = true;
		if (event.type === "tool_call.start") {
			if (!record.allowedToolNames.has(event.name)) {
				this.protocolViolation(record, "PROTOCOL_ERROR", "Provider selected an undeclared tool");
				return false;
			}
			if (record.toolCalls.has(event.toolUseId)) {
				this.protocolViolation(record, "PROTOCOL_ERROR", "Duplicate toolUseId");
				return false;
			}
			record.toolCalls.set(event.toolUseId, { mode: "streaming", ended: false, bytes: 0 });
			record.exposedToolCall = true;
			record.hasVisibleOutput = true;
		}
		if (event.type === "tool_call.delta") {
			const state = record.toolCalls.get(event.toolUseId);
			if (!state || state.mode !== "streaming" || state.ended) {
				this.protocolViolation(record, "PROTOCOL_ERROR", "tool_call.delta has no open start");
				return false;
			}
			const bytes = utf8Bytes(event.argumentsDelta);
			if (bytes > this.limits.maxDeltaBytes) {
				this.protocolViolation(record, "FRAME_LIMIT", "tool_call.delta exceeded the delta limit");
				return false;
			}
			state.bytes += bytes;
			record.allToolArgumentBytes += bytes;
			if (
				state.bytes > this.limits.maxToolArgumentBytes ||
				record.allToolArgumentBytes > this.limits.maxAllToolArgumentBytes
			) {
				this.outputLimit(record, "Provider tool arguments exceeded the limit");
				return false;
			}
		}
		if (event.type === "tool_call.end") {
			const state = record.toolCalls.get(event.toolUseId);
			if (!state || state.mode !== "streaming" || state.ended) {
				this.protocolViolation(record, "PROTOCOL_ERROR", "tool_call.end has no open start");
				return false;
			}
			state.ended = true;
		}
		if (event.type === "tool_call.complete") {
			if (!record.allowedToolNames.has(event.name)) {
				this.protocolViolation(record, "PROTOCOL_ERROR", "Provider selected an undeclared tool");
				return false;
			}
			if (record.toolCalls.has(event.toolUseId)) {
				this.protocolViolation(record, "PROTOCOL_ERROR", "Duplicate toolUseId");
				return false;
			}
			const bytes = byteLength(event.input);
			if (bytes > this.limits.maxToolArgumentBytes) {
				this.outputLimit(record, "Provider tool arguments exceeded the limit");
				return false;
			}
			record.allToolArgumentBytes += bytes;
			if (record.allToolArgumentBytes > this.limits.maxAllToolArgumentBytes) {
				this.outputLimit(record, "Provider tool arguments exceeded the total limit");
				return false;
			}
			record.toolCalls.set(event.toolUseId, { mode: "complete", ended: true, bytes });
			record.exposedToolCall = true;
			record.hasVisibleOutput = true;
		}
		return true;
	}

	private consumeCredit(
		record: OperationRecord,
		kind: "normal" | "terminal",
		bodyBytes: number,
	): boolean {
		if (kind === "normal") {
			if (
				record.usedNormalEvents + 1 > this.streamWindow.maxUnackedEvents ||
				record.usedNormalBytes + bodyBytes > this.streamWindow.maxUnackedBytes
			) {
				this.protocolViolation(record, "CREDIT_EXCEEDED", "Provider exceeded normal stream credit");
				return false;
			}
			record.usedNormalEvents += 1;
			record.usedNormalBytes += bodyBytes;
			return true;
		}
		if (
			record.usedTerminalEvents + 1 > this.streamWindow.terminalReserveEvents ||
			record.usedTerminalBytes + bodyBytes > this.streamWindow.terminalReserveBytes
		) {
			this.protocolViolation(
				record,
				"CREDIT_EXCEEDED",
				"Provider exceeded terminal stream reserve",
			);
			return false;
		}
		record.usedTerminalEvents += 1;
		record.usedTerminalBytes += bodyBytes;
		return true;
	}

	private releaseCredit(
		record: OperationRecord,
		kind: "normal" | "terminal",
		bodyBytes: number,
	): void {
		if (kind === "normal") {
			record.usedNormalEvents = Math.max(0, record.usedNormalEvents - 1);
			record.usedNormalBytes = Math.max(0, record.usedNormalBytes - bodyBytes);
		} else {
			record.usedTerminalEvents = Math.max(0, record.usedTerminalEvents - 1);
			record.usedTerminalBytes = Math.max(0, record.usedTerminalBytes - bodyBytes);
		}
	}

	private enqueueEvent(record: OperationRecord, queued: QueuedEvent): void {
		if (
			record.queue.length + 1 > this.limits.maxQueueEvents ||
			record.queuedBytes + queued.bodyBytes > this.limits.maxQueueBytes ||
			this.queuedBytes + queued.bodyBytes > this.limits.maxTotalQueueBytes
		) {
			this.releaseCredit(record, queued.creditKind, queued.bodyBytes);
			this.protocolViolation(record, "QUEUE_LIMIT", "Provider event queue exceeded its limit");
			return;
		}
		record.queue.push(queued);
		record.queuedBytes += queued.bodyBytes;
		this.queuedBytes += queued.bodyBytes;
		if (record.idleTimer) clearTimeout(record.idleTimer);
		record.idleTimer = undefined;
		this.pumpWaiter(record);
	}

	private nextOperationEvent(
		record: OperationRecord,
	): Promise<IteratorResult<ProviderStreamEvent>> {
		if (record.waiter) {
			return Promise.reject(
				new ProviderRpcError("PROTOCOL_ERROR", "Concurrent operation event reads are not allowed", {
					operationId: record.operationId,
					requestId: record.requestId,
				}),
			);
		}
		const immediate = this.takeNextEvent(record);
		if (immediate) return immediate;
		return new Promise((resolve, reject) => {
			record.waiter = { resolve, reject };
			this.pumpWaiter(record);
		});
	}

	private takeNextEvent(
		record: OperationRecord,
	): Promise<IteratorResult<ProviderStreamEvent>> | undefined {
		const queued = record.queue.shift();
		if (queued) {
			record.queuedBytes -= queued.bodyBytes;
			this.queuedBytes -= queued.bodyBytes;
			if (queued.creditKind === "normal") {
				this.releaseCredit(record, "normal", queued.bodyBytes);
				void this.transport
					.notify("provider.streamAck", {
						protocolVersion: this.selectedProtocolVersion,
						operationId: record.operationId,
						throughSeq: queued.seq,
						grantEvents: 1,
						grantBytes: queued.bodyBytes,
					})
					.catch((error) => this.handleTransportClose(asError(error)));
			}
			if (queued.event.type === "done") {
				const postDoneError = record.postDoneError;
				record.waiter = undefined;
				this.finishOperation(record);
				return Promise.resolve({ done: false, value: queued.event }).then((result) => {
					if (postDoneError) record.terminalError = postDoneError;
					return result;
				});
			}
			if (record.queue.length === 0) this.armIdleTimer(record);
			return Promise.resolve({ done: false, value: queued.event });
		}
		if (record.terminalError) {
			const error = record.terminalError;
			record.waiter = undefined;
			this.finishOperation(record);
			return Promise.reject(error);
		}
		if (record.state === "closed") return Promise.resolve({ done: true, value: undefined });
		if (record.state === "terminal_received") {
			record.waiter = undefined;
			this.finishOperation(record);
			return record.postDoneError
				? Promise.reject(record.postDoneError)
				: Promise.resolve({ done: true, value: undefined });
		}
		this.armIdleTimer(record);
		return undefined;
	}

	private pumpWaiter(record: OperationRecord): void {
		const waiter = record.waiter;
		if (!waiter) return;
		const next = this.takeNextEvent(record);
		if (!next) return;
		record.waiter = undefined;
		void next.then(waiter.resolve, waiter.reject);
	}

	private armIdleTimer(record: OperationRecord): void {
		if (
			record.queue.length > 0 ||
			!record.accepted ||
			record.state !== "streaming" ||
			this.limits.streamIdleTimeoutMs <= 0
		) {
			return;
		}
		if (record.idleTimer) clearTimeout(record.idleTimer);
		record.idleTimer = setTimeout(() => {
			void this.beginCancel(
				record,
				"timeout",
				"Provider stream became idle",
				new ProviderRpcError(
					"STREAM_IDLE_TIMEOUT",
					`Provider stream idle timeout after ${this.limits.streamIdleTimeoutMs}ms`,
					{
						operationId: record.operationId,
						requestId: record.requestId,
					},
				),
			);
		}, this.limits.streamIdleTimeoutMs);
	}

	private beginCancel(
		record: OperationRecord,
		reason: ProviderCancelReason,
		message: string | undefined,
		terminalError: Error,
	): Promise<ProviderCancelResult> {
		if (record.state === "terminal_received" || record.state === "closed") {
			return Promise.resolve({ operationId: record.operationId, state: "already_done" });
		}
		if (record.cancelPromise) return record.cancelPromise;
		record.state = "cancelling";
		record.postDoneError = terminalError;
		if (record.idleTimer) clearTimeout(record.idleTimer);
		record.idleTimer = undefined;
		const protocolVersion = this.selectedProtocolVersion ?? PROVIDER_PROTOCOL_VERSION;
		record.cancelPromise = this.transport
			.request<unknown>(
				"provider.cancel",
				{
					protocolVersion,
					operationId: record.operationId,
					reason,
					...(message ? { message } : {}),
				},
				{ timeoutMs: this.limits.acceptedTimeoutMs, requestId: this.nextRequestId() },
			)
			.then((result) => normalizeCancelResult(result, record.operationId))
			.catch(() => ({
				operationId: record.operationId,
				state:
					record.state === "terminal_received" || record.state === "closed"
						? ("already_done" as const)
						: ("cancelling" as const),
			}));
		record.cancelTimer = setTimeout(() => {
			if (!this.operations.has(record.operationId) || record.state === "terminal_received") return;
			this.failOperation(record, terminalError);
			void this.killTransport(`provider cancel grace expired: ${record.operationId}`);
		}, this.limits.cancelGraceMs);
		return record.cancelPromise;
	}

	private outputLimit(record: OperationRecord, message: string): void {
		void this.beginCancel(
			record,
			"output_limit",
			message,
			new ProviderRpcError("OUTPUT_LIMIT", message, {
				operationId: record.operationId,
				requestId: record.requestId,
				exposedToolCall: record.exposedToolCall,
			}),
		);
	}

	private protocolViolation(
		record: OperationRecord | undefined,
		code: Extract<
			ProviderRpcErrorCode,
			"PROTOCOL_ERROR" | "FRAME_LIMIT" | "QUEUE_LIMIT" | "CREDIT_EXCEEDED"
		>,
		message: string,
	): void {
		const error = new ProviderRpcError(code, message, {
			operationId: record?.operationId,
			requestId: record?.requestId,
			exposedToolCall: record?.exposedToolCall,
		});
		this.protocolErrors += 1;
		this.onProtocolViolation?.(error);
		if (record) this.failOperation(record, error);
		else
			for (const operation of [...this.operations.values()]) this.failOperation(operation, error);
		void this.killTransport(message);
	}

	private recordLateEvent(operationId: string): void {
		this.lateEvents += 1;
		this.closedOperationIds.add(operationId);
		if (this.lateEvents > this.limits.maxLateEvents) {
			this.protocolViolation(
				undefined,
				"PROTOCOL_ERROR",
				"Provider repeatedly emitted late events",
			);
		}
	}

	private failOperation(record: OperationRecord, error: Error): void {
		if (record.state === "closed" || record.state === "failed") return;
		record.state = "failed";
		record.terminalError = error;
		this.clearOperationTimers(record);
		this.pumpWaiter(record);
		if (!record.iteratorClaimed && record.queue.length === 0) this.finishOperation(record);
	}

	private finishOperation(record: OperationRecord): void {
		if (record.state === "closed") return;
		this.clearOperationTimers(record);
		record.state = "closed";
		record.removeAbort?.();
		record.removeAbort = undefined;
		record.preAcceptedEvents = [];
		record.preAcceptedBytes = 0;
		this.operations.delete(record.operationId);
		this.requests.delete(record.requestId);
		this.closedOperationIds.add(record.operationId);
		while (this.closedOperationIds.size > 1_024) {
			const oldest = this.closedOperationIds.values().next().value;
			if (typeof oldest !== "string") break;
			this.closedOperationIds.delete(oldest);
		}
		if (record.queue.length > 0) {
			for (const queued of record.queue) {
				record.queuedBytes -= queued.bodyBytes;
				this.queuedBytes -= queued.bodyBytes;
			}
			record.queue.length = 0;
		}
		if (record.waiter) {
			const waiter = record.waiter;
			record.waiter = undefined;
			if (record.terminalError) waiter.reject(record.terminalError);
			else waiter.resolve({ done: true, value: undefined });
		}
	}

	private clearOperationTimers(record: OperationRecord): void {
		if (record.cancelTimer) clearTimeout(record.cancelTimer);
		if (record.idleTimer) clearTimeout(record.idleTimer);
		if (record.totalTimer) clearTimeout(record.totalTimer);
		record.cancelTimer = undefined;
		record.idleTimer = undefined;
		record.totalTimer = undefined;
	}

	private async killTransport(reason: string): Promise<void> {
		if (this.transportKilled) return;
		this.transportKilled = true;
		try {
			await this.transport.kill?.(reason);
		} catch {
			// The transport is already unusable; fail-closed state is preserved locally.
		}
	}

	private assertUsable(): void {
		if (this.disposed)
			throw new ProviderRpcError("TRANSPORT_ERROR", "Provider RPC client disposed");
		if (this.transportKilled) {
			throw new ProviderRpcError("TRANSPORT_ERROR", "Provider RPC transport is closed");
		}
	}

	private requireProtocolVersion(): string {
		this.assertUsable();
		if (!this.selectedProtocolVersion) {
			throw new ProviderRpcError("NOT_DESCRIBED", "provider.describe must complete first");
		}
		return this.selectedProtocolVersion;
	}

	private requireDescriptor(providerTypeId: string): ProviderDescriptor {
		const descriptor = this.descriptors.get(providerTypeId);
		if (!descriptor) {
			throw new ProviderRpcError("INVALID_RESPONSE", `Unknown provider type: ${providerTypeId}`);
		}
		return descriptor;
	}

	private assertConfigLimit(providerTypeId: string, config: Record<string, JsonValue>): void {
		const limit = this.requireDescriptor(providerTypeId).limits.maxConfigBytes;
		if (byteLength(config) > limit) {
			throw new ProviderRpcError("OUTPUT_LIMIT", "Provider config exceeded its byte limit");
		}
	}

	private assertRequestSize(value: unknown, method: string): void {
		if (byteLength(value) > this.limits.maxRequestBytes) {
			throw new ProviderRpcError("OUTPUT_LIMIT", `${method} request exceeded its byte limit`);
		}
	}

	/**
	 * @param declaredMax Optional manifest-declared ceiling. Only ever tightens the host limit;
	 * a plugin cannot raise its own budget by declaring a larger number.
	 */
	private assertUnarySize(value: unknown, method: string, declaredMax?: number): void {
		const limit =
			declaredMax != null && Number.isFinite(declaredMax)
				? Math.min(declaredMax, this.limits.maxUnaryResponseBytes)
				: this.limits.maxUnaryResponseBytes;
		if (byteLength(value) > limit) {
			throw new ProviderRpcError("FRAME_LIMIT", `${method} response exceeded its byte limit`);
		}
	}

	private nextRequestId(): string {
		return this.idFactory("rpc");
	}

	private nextUniqueId(prefix: "op" | "rpc", map: Map<string, unknown>): string {
		for (let attempt = 0; attempt < 10; attempt++) {
			const id = this.idFactory(prefix);
			if (id && !map.has(id) && !this.closedOperationIds.has(id)) return id;
		}
		throw new ProviderRpcError("PROTOCOL_ERROR", `Could not allocate a unique ${prefix} ID`);
	}
}

/** Short name for callers that do not need to distinguish plugin providers. */
export { PluginProviderRpcClient as ProviderRpcClient };

function isTransport(
	value: PluginProviderRpcClientOptions | ProviderRpcTransport,
): value is ProviderRpcTransport {
	return typeof (value as ProviderRpcTransport).request === "function";
}

function normalizeProtocolVersions(versions: string[]): string[] {
	const unique = [...new Set(versions.map((version) => version.trim()).filter(Boolean))];
	if (unique.length === 0 || unique.some((version) => !/^\d+\.\d+$/.test(version))) {
		throw new ProviderRpcError("INCOMPATIBLE_PROTOCOL", "Invalid provider protocol version list");
	}
	return unique.sort(compareVersions).reverse();
}

function compareVersions(left: string, right: string): number {
	const [leftMajor, leftMinor] = left.split(".").map(Number);
	const [rightMajor, rightMinor] = right.split(".").map(Number);
	return leftMajor - rightMajor || leftMinor - rightMinor;
}

function normalizeWindow(input: Partial<ProviderStreamWindow> | undefined): ProviderStreamWindow {
	const window = { ...DEFAULT_STREAM_WINDOW, ...(input ?? {}) };
	for (const [key, value] of Object.entries(window)) {
		if (!Number.isSafeInteger(value) || value <= 0) {
			throw new RangeError(`${key} must be a positive safe integer`);
		}
	}
	return window;
}

function normalizeLimits(
	input: Partial<ProviderRpcLimits> | undefined,
	window: ProviderStreamWindow,
): ProviderRpcLimits {
	const result = { ...DEFAULT_LIMITS, ...(input ?? {}) };
	result.maxQueueEvents = Math.max(
		result.maxQueueEvents,
		window.maxUnackedEvents + window.terminalReserveEvents,
	);
	result.maxQueueBytes = Math.max(
		result.maxQueueBytes,
		window.maxUnackedBytes + window.terminalReserveBytes,
	);
	for (const [key, value] of Object.entries(result)) {
		if (!Number.isSafeInteger(value) || value <= 0) {
			throw new RangeError(`${key} must be a positive safe integer`);
		}
	}
	return result;
}

function normalizeDescribeResult(
	value: unknown,
	offeredVersions: string[],
	expectedPluginId?: string,
): ProviderDescribeResult {
	const record = requireRecord(value, "provider.describe result");
	const selectedProtocolVersion = requireString(
		record.selectedProtocolVersion,
		"selectedProtocolVersion",
	);
	if (!offeredVersions.includes(selectedProtocolVersion)) {
		throw new ProviderRpcError(
			"INCOMPATIBLE_PROTOCOL",
			`Plugin selected unsupported provider protocol ${selectedProtocolVersion}`,
		);
	}
	const plugin = requireRecord(record.plugin, "plugin");
	const pluginId = requireString(plugin.id, "plugin.id");
	if (expectedPluginId && pluginId !== expectedPluginId) {
		throw new ProviderRpcError("INVALID_RESPONSE", "provider.describe plugin identity mismatch");
	}
	const providersValue = record.providers;
	if (!Array.isArray(providersValue)) {
		throw new ProviderRpcError("INVALID_RESPONSE", "provider.describe providers must be an array");
	}
	const seen = new Set<string>();
	const providers = providersValue.map((providerValue) => {
		const provider = requireRecord(providerValue, "provider descriptor");
		const localId = requireString(provider.localId, "provider.localId");
		if (!/^[a-z][a-z0-9._-]{0,63}$/.test(localId) || seen.has(localId)) {
			throw new ProviderRpcError("INVALID_RESPONSE", "Invalid or duplicate provider localId");
		}
		seen.add(localId);
		const capabilities = requireRecord(provider.capabilities, "provider.capabilities");
		if (
			capabilities.validateConfig !== true ||
			capabilities.listModels !== true ||
			capabilities.chat !== true ||
			typeof capabilities.generate !== "boolean"
		) {
			throw new ProviderRpcError("INVALID_RESPONSE", "Provider capabilities are incomplete");
		}
		const configSchema = requireRecord(provider.configSchema, "provider.configSchema") as Record<
			string,
			JsonValue
		>;
		assertNoSecretDefaults(configSchema);
		const limits =
			provider.limits === undefined ? {} : requireRecord(provider.limits, "provider.limits");
		return {
			pluginId,
			providerTypeId: `${pluginId}/${localId}`,
			localId,
			displayName: requireString(provider.displayName, "provider.displayName"),
			...(optionalString(provider.description)
				? { description: String(provider.description) }
				: {}),
			configSchema: cloneJson(configSchema),
			...(optionalString(provider.defaultModelId)
				? { defaultModelId: String(provider.defaultModelId) }
				: {}),
			capabilities: {
				validateConfig: true as const,
				listModels: true as const,
				chat: true as const,
				generate: capabilities.generate,
				...(typeof capabilities.reasoningContinuation === "boolean"
					? { reasoningContinuation: capabilities.reasoningContinuation }
					: {}),
				...(typeof capabilities.inputImages === "boolean"
					? { inputImages: capabilities.inputImages }
					: {}),
				...(typeof capabilities.mayLeakXmlToolCalls === "boolean"
					? { mayLeakXmlToolCalls: capabilities.mayLeakXmlToolCalls }
					: {}),
			},
			limits: {
				maxConcurrentChat: positiveInteger(limits.maxConcurrentChat, 1),
				maxConcurrentGenerate: positiveInteger(limits.maxConcurrentGenerate, 1),
				maxConfigBytes: positiveInteger(limits.maxConfigBytes, 1024 * 1024),
				maxModelPageSize: Math.min(200, positiveInteger(limits.maxModelPageSize, 200)),
			},
		} satisfies ProviderDescriptor;
	});
	return {
		selectedProtocolVersion,
		plugin: {
			id: pluginId,
			name: requireString(plugin.name, "plugin.name"),
			version: requireString(plugin.version, "plugin.version"),
		},
		providers,
	};
}

function normalizeValidateConfigResult(value: unknown): ValidateConfigResult {
	const record = requireRecord(value, "provider.validateConfig result");
	if (typeof record.valid !== "boolean" || !Array.isArray(record.issues)) {
		throw new ProviderRpcError("INVALID_RESPONSE", "Invalid provider.validateConfig result");
	}
	const issues = record.issues.map((issueValue) => {
		const issue = requireRecord(issueValue, "validation issue");
		if (!isOneOf(issue.severity, ["error", "warning", "info"] as const)) {
			throw new ProviderRpcError("INVALID_RESPONSE", "Invalid validation issue severity");
		}
		return {
			severity: issue.severity,
			code: requireString(issue.code, "validation issue code"),
			...(optionalString(issue.path) ? { path: String(issue.path) } : {}),
			message: requireString(issue.message, "validation issue message"),
			...(typeof issue.retryable === "boolean" ? { retryable: issue.retryable } : {}),
		} satisfies ValidateConfigIssue;
	});
	return {
		valid: record.valid,
		issues,
		...(record.capabilities === undefined
			? {}
			: {
					capabilities: cloneJson(
						requireRecord(record.capabilities, "validation capabilities") as Record<
							string,
							JsonValue
						>,
					),
				}),
	};
}

/** Max hits accepted from one `provider.search` response. Matches the protocol schema. */
const MAX_SEARCH_RESULTS = 100;

function optionalSearchString(
	value: unknown,
	label: string,
	maxLength: number,
): string | undefined {
	if (value === undefined || value === null) return undefined;
	if (typeof value !== "string") {
		throw new ProviderRpcError("INVALID_RESPONSE", `${label} must be a string`);
	}
	if (value.length > maxLength) {
		throw new ProviderRpcError("OUTPUT_LIMIT", `${label} exceeded its length limit`);
	}
	return value.length > 0 ? value : undefined;
}

function normalizeSearchResult(value: unknown): ProviderSearchResult {
	const record = requireRecord(value, `${PROVIDER_SEARCH_METHOD} result`);
	const text = optionalSearchString(record.text, "search.text", 1_000_000);
	let results: ProviderSearchResultItem[] | undefined;
	if (record.results !== undefined && record.results !== null) {
		if (!Array.isArray(record.results) || record.results.length > MAX_SEARCH_RESULTS) {
			throw new ProviderRpcError("INVALID_RESPONSE", "Invalid or oversized search result page");
		}
		results = record.results.map((itemValue) => {
			const item = requireRecord(itemValue, "search result");
			return {
				title: optionalSearchString(item.title, "search result title", 1_000),
				url: optionalSearchString(item.url, "search result url", 2_048),
				snippet: optionalSearchString(item.snippet, "search result snippet", 8_000),
				publishedAt: optionalSearchString(item.publishedAt, "search result publishedAt", 64),
				source: optionalSearchString(item.source, "search result source", 200),
			};
		});
	}
	if (!text && !results?.length) {
		// An empty response would otherwise count as a successful search with no content,
		// stopping the router's fallback chain at a channel that returned nothing.
		throw new ProviderRpcError(
			"INVALID_RESPONSE",
			`${PROVIDER_SEARCH_METHOD} result must carry text or results`,
		);
	}
	return { ...(text ? { text } : {}), ...(results?.length ? { results } : {}) };
}

function normalizeModelCatalog(value: unknown, maximum: number): ModelCatalog {
	const record = requireRecord(value, "provider.listModels result");
	if (!Array.isArray(record.models) || record.models.length > maximum) {
		throw new ProviderRpcError("INVALID_RESPONSE", "Invalid or oversized provider model page");
	}
	const ids = new Set<string>();
	const models = record.models.map((modelValue) => {
		const model = requireRecord(modelValue, "provider model");
		const id = requireString(model.id, "model.id");
		if (utf8Bytes(id) > 256 || hasControlCharacters(id) || id.startsWith("__") || ids.has(id)) {
			throw new ProviderRpcError("INVALID_RESPONSE", "Invalid or duplicate provider model ID");
		}
		ids.add(id);
		const capabilities = requireRecord(model.capabilities, "model.capabilities");
		for (const key of ["chat", "generate", "streaming", "tools"] as const) {
			if (typeof capabilities[key] !== "boolean") {
				throw new ProviderRpcError("INVALID_RESPONSE", `Missing model capability: ${key}`);
			}
		}
		const chat = capabilities.chat as boolean;
		const generate = capabilities.generate as boolean;
		const streaming = capabilities.streaming as boolean;
		const tools = capabilities.tools as boolean;
		const sessionMode = capabilities.sessionMode ?? "stateful";
		if (!isOneOf(sessionMode, ["stateless", "stateful"] as const)) {
			throw new ProviderRpcError("INVALID_RESPONSE", "Invalid model session mode");
		}
		const rawReasoningEfforts = capabilities.reasoningEfforts;
		if (
			rawReasoningEfforts !== undefined &&
			(!Array.isArray(rawReasoningEfforts) ||
				rawReasoningEfforts.some(
					(item) => !isOneOf(item, ["none", "low", "medium", "high", "xhigh", "max"] as const),
				))
		) {
			throw new ProviderRpcError("INVALID_RESPONSE", "Invalid model reasoning efforts");
		}
		const reasoningEfforts = rawReasoningEfforts as
			| Array<"none" | "low" | "medium" | "high" | "xhigh" | "max">
			| undefined;
		return {
			id,
			displayName: requireString(model.displayName, "model.displayName"),
			...(optionalString(model.description) ? { description: String(model.description) } : {}),
			...(stringArray(model.aliases) ? { aliases: stringArray(model.aliases) } : {}),
			...(safePositiveInteger(model.contextWindow)
				? { contextWindow: Number(model.contextWindow) }
				: {}),
			...(safePositiveInteger(model.maxOutputTokens)
				? { maxOutputTokens: Number(model.maxOutputTokens) }
				: {}),
			...(typeof model.deprecated === "boolean" ? { deprecated: model.deprecated } : {}),
			...(optionalString(model.deprecationMessage)
				? { deprecationMessage: String(model.deprecationMessage) }
				: {}),
			capabilities: {
				chat,
				generate,
				streaming,
				tools,
				sessionMode,
				...(typeof capabilities.parallelToolCalls === "boolean"
					? { parallelToolCalls: capabilities.parallelToolCalls }
					: {}),
				...(typeof capabilities.inputImages === "boolean"
					? { inputImages: capabilities.inputImages }
					: {}),
				...(typeof capabilities.reasoning === "boolean"
					? { reasoning: capabilities.reasoning }
					: {}),
				...(reasoningEfforts ? { reasoningEfforts: [...reasoningEfforts] } : {}),
			},
			...(model.metadata === undefined
				? {}
				: {
						metadata: cloneJson(
							requireRecord(model.metadata, "model.metadata") as Record<string, JsonValue>,
						),
					}),
		} satisfies ProviderModelDescriptor;
	});
	return {
		models,
		...(optionalString(record.nextCursor) ? { nextCursor: String(record.nextCursor) } : {}),
		...(optionalString(record.catalogVersion)
			? { catalogVersion: String(record.catalogVersion) }
			: {}),
		...(safePositiveInteger(record.cacheTtlMs) ? { cacheTtlMs: Number(record.cacheTtlMs) } : {}),
		...(typeof record.stale === "boolean" ? { stale: record.stale } : {}),
	};
}

function normalizeAcceptedResult(value: unknown, operationId: string): AcceptedResult {
	const record = requireRecord(value, "provider accepted result");
	if (record.accepted !== true || record.operationId !== operationId) {
		throw new ProviderRpcError("INVALID_RESPONSE", "Provider returned an invalid accepted result", {
			operationId,
		});
	}
	return { accepted: true, operationId };
}

function normalizeCancelResult(value: unknown, operationId: string): ProviderCancelResult {
	const record = requireRecord(value, "provider.cancel result");
	if (
		record.operationId !== operationId ||
		!isOneOf(record.state, ["cancelling", "already_done", "unknown_operation"] as const)
	) {
		throw new ProviderRpcError("INVALID_RESPONSE", "Provider returned an invalid cancel result", {
			operationId,
		});
	}
	return { operationId, state: record.state };
}

function requireRecord(value: unknown, label: string): Record<string, unknown> {
	if (typeof value !== "object" || value === null || Array.isArray(value)) {
		throw new ProviderRpcError("INVALID_RESPONSE", `${label} must be an object`);
	}
	return value as Record<string, unknown>;
}

function requireString(value: unknown, label: string): string {
	if (typeof value !== "string" || !value.trim()) {
		throw new ProviderRpcError("INVALID_RESPONSE", `${label} must be a non-empty string`);
	}
	return value;
}

function optionalString(value: unknown): value is string {
	return typeof value === "string" && value.length > 0;
}

function stringArray(value: unknown): string[] | undefined {
	if (value === undefined) return undefined;
	if (!Array.isArray(value) || value.some((item) => typeof item !== "string" || !item)) {
		throw new ProviderRpcError("INVALID_RESPONSE", "Expected an array of non-empty strings");
	}
	return [...new Set(value)];
}

function positiveInteger(value: unknown, fallback: number): number {
	if (value === undefined) return fallback;
	if (!safePositiveInteger(value)) {
		throw new ProviderRpcError("INVALID_RESPONSE", "Expected a positive safe integer");
	}
	return value;
}

function safePositiveInteger(value: unknown): value is number {
	return typeof value === "number" && Number.isSafeInteger(value) && value > 0;
}

function isOneOf<const T extends readonly unknown[]>(
	value: unknown,
	values: T,
): value is T[number] {
	return values.includes(value);
}

function assertNoSecretDefaults(schema: Record<string, JsonValue>): void {
	const visit = (value: JsonValue): void => {
		if (!value || typeof value !== "object") return;
		if (Array.isArray(value)) {
			for (const item of value) visit(item);
			return;
		}
		const secret = value["x-narrafork-secret"] === true || value.writeOnly === true;
		if (secret && Object.hasOwn(value, "default")) {
			throw new ProviderRpcError(
				"INVALID_RESPONSE",
				"Secret config schema fields cannot have defaults",
			);
		}
		for (const nested of Object.values(value)) visit(nested);
	};
	visit(schema);
}

function cloneJson<T>(value: T): T {
	return structuredClone(value);
}

function byteLength(value: unknown): number {
	try {
		return textEncoder.encode(JSON.stringify(value)).byteLength;
	} catch (error) {
		throw new ProviderRpcError("INVALID_RESPONSE", "Provider RPC value is not JSON serializable", {
			cause: error,
		});
	}
}

function utf8Bytes(value: string): number {
	return textEncoder.encode(value).byteLength;
}

function hasControlCharacters(value: string): boolean {
	for (const character of value) {
		const point = character.codePointAt(0) ?? 0;
		if (point < 0x20 || point === 0x7f) return true;
	}
	return false;
}

function createAbortError(reason?: unknown): Error {
	const error = new Error(reason instanceof Error ? reason.message : "The operation was aborted");
	error.name = "AbortError";
	return error;
}

function cancelErrorFor(reason: ProviderCancelReason, record: OperationRecord): Error {
	if (reason === "user_abort" || reason === "superseded" || reason === "shutdown") {
		return createAbortError();
	}
	return new ProviderRpcError(
		reason === "output_limit" ? "OUTPUT_LIMIT" : "OPERATION_TIMEOUT",
		reason === "output_limit" ? "Provider output limit reached" : "Provider operation timed out",
		{ operationId: record.operationId, requestId: record.requestId },
	);
}

function asError(error: unknown): Error {
	return error instanceof Error ? error : new Error(String(error));
}
